;;;; cl-cc.asd - canonical ASDF system definition for CL-CC
(eval-when (:compile-toplevel :load-toplevel :execute)
  ;; Keep the canonical ASDF entrypoint runnable in a fresh SBCL by
  ;; opportunistically loading a user-local Quicklisp when dependencies are absent.
  (labels ((quicklisp-setup-candidates ()
             (let ((home (user-homedir-pathname)))
               (remove nil
                       (list (and home
                                  (merge-pathnames #P"quicklisp/setup.lisp" home))
                             #P"C:/quicklisp/setup.lisp"
                             #P"D:/quicklisp/setup.lisp"))))
           (ensure-quicklisp-dependencies ()
             (unless (ignore-errors (asdf:find-system "alexandria"))
               (loop for candidate in (quicklisp-setup-candidates)
                     for setup = (and candidate (probe-file candidate))
                     when setup
                       do (load setup :verbose nil :print nil)
                          (return t)))))
    (ensure-quicklisp-dependencies)))

(asdf:defsystem "cl-cc"
  :version "0.1.0"
  :description "CL-CC: 纯 Common Lisp Claude Code CLI 核心实现"
  :author "CL-CC Team"
  :license "MIT"
  :depends-on ("alexandria" "uiop" "cl-ppcre")
  :in-order-to ((test-op (test-op "cl-cc/tests")))
  :serial t
  :components ((:file "src/package")
               (:file "src/lib/package")
               (:file "src/lib/text")
               (:file "src/lib/time")
               (:file "src/lib/errors")
               (:file "src/lib/result")
               (:file "src/lib/debug-log")
               (:file "src/lib/git-context")
               (:file "src/lib/json")
               (:file "src/models/package")
               (:file "src/models/command-definition")
               (:file "src/models/tool-definition")
               (:file "src/models/session-state")
               (:file "src/models/execution-cycle")
               (:file "src/models/permission-decision")
               (:file "src/models/compatibility-fixture")
               (:file "src/session/package")
               (:file "src/session/serializer")
               (:file "src/session/store")
               (:file "src/tools/package")
               (:file "src/tools/echo-tool")
               (:file "src/tools/failing-tool")
               (:file "src/tools/file-read-tool")
               (:file "src/tools/file-write-tool")
               (:file "src/tools/shell-tool")
               (:file "src/tools/shell-task-list-tool")
               (:file "src/tools/shell-task-detail-tool")
               (:file "src/tools/shell-task-tool")
               (:file "src/tools/shell-task-cleanup-tool")
               (:file "src/tools/shell-task-output-tool")
               (:file "src/tools/file-edit-tool")
               (:file "src/tools/directory-list-tool")
               (:file "src/tools/grep-tool")
               (:file "src/tools/registry")
               (:file "src/services/package")
               (:file "src/core/package")
               (:file "src/core/command-schema-builders")
               (:file "src/core/command-argument-parsing")
               (:file "src/core/command-resolution")
               (:file "src/core/command-registry")
               (:file "src/core/execution-context")
               (:file "src/core/execution-engine")
               (:file "src/core/session-loop")
               (:file "src/services/permission-policy")
               (:file "src/services/permission-audit")
               (:file "src/services/fixture-loader")
               (:file "src/services/tool-selection")
               (:file "src/services/tool-runner")
               (:file "src/services/golden-regression")
               (:file "src/services/session-service")
               (:file "src/services/schema-validation")
               (:file "src/cli/argv")
               (:file "src/cli/result-rendering")
               (:file "src/cli/help-command")
               (:file "src/cli/session-command")
               (:file "src/cli/session-list-command")
               (:file "src/cli/session-resume-command")
               (:file "src/cli/session-run-command")
               (:file "src/cli/chat-command")
               (:file "src/cli/run-command")
               (:file "src/cli/main")))

(asdf:defsystem "cl-cc/tests"
  :depends-on ("cl-cc" "fiveam")
  :perform (asdf:test-op (op component)
                         (declare (ignore op component))
                         (uiop:symbol-call :cl-cc/tests :run-tests))
  :serial t
  :components ((:file "tests/test-package")
               (:file "tests/contract/fixture-helpers")
               (:file "tests/unit/lib-text-test")
               (:file "tests/unit/lib-time-test")
               (:file "tests/unit/lib-git-context-test")
               (:file "tests/unit/argv-parser-test")
               (:file "tests/unit/models-test")
               (:file "tests/unit/file-read-tool-test")
               (:file "tests/unit/file-write-tool-test")
               (:file "tests/unit/shell-tool-test")
               (:file "tests/unit/shell-task-list-tool-test")
               (:file "tests/unit/shell-task-detail-tool-test")
               (:file "tests/unit/shell-task-tool-test")
               (:file "tests/unit/shell-task-cleanup-tool-test")
               (:file "tests/unit/shell-task-output-tool-test")
               (:file "tests/unit/file-edit-tool-test")
               (:file "tests/unit/directory-list-tool-test")
               (:file "tests/unit/grep-tool-test")
               (:file "tests/unit/tool-registry-test")
               (:file "tests/unit/command-schema-builders-test")
               (:file "tests/unit/command-argument-parsing-test")
               (:file "tests/unit/command-registry-metadata-test")
               (:file "tests/unit/command-resolution-test")
               (:file "tests/unit/chat-command-test")
               (:file "tests/unit/help-command-rendering-test")
               (:file "tests/unit/json-parser-test")
               (:file "tests/unit/schema-validation-test")
               (:file "tests/unit/execution-cycle-test")
               (:file "tests/unit/execution-engine-test")
               (:file "tests/unit/tool-selection-test")
               (:file "tests/unit/command-dispatch-test")
               (:file "tests/unit/permission-audit-test")
               (:file "tests/unit/permission-policy-test")
               (:file "tests/unit/session-service-test")
               (:file "tests/unit/session-store-test")
               (:file "tests/unit/cli-output-test")
               (:file "tests/integration/session-start-test")
               (:file "tests/integration/session-resume-test")
               (:file "tests/integration/tool-execution-test")
               (:file "tests/contract/cli-help-contract-test")
               (:file "tests/contract/cli-json-output-contract-test")
               (:file "tests/contract/result-schema-contract-test")
               (:file "tests/contract/permission-contract-test")
               (:file "tests/contract/golden-regression-test")
               (:file "tests/contract/run-fixture-contract-test")
               (:file "tests/run-tests")))