;;;; project.asd - ASDF system definition for CL-CC Core
(asdf:defsystem "cl-cc"
  :version "0.1.0"
  :description "CL-CC: 纯 Common Lisp Claude Code CLI 核心实现"
  :author "CL-CC Team"
  :license "MIT"
  :depends-on ("alexandria" "uiop")
  :serial t
  :components ((:file "src/package")
               (:file "src/lib/package")
               (:file "src/lib/errors")
               (:file "src/lib/result")
               (:file "src/lib/debug-log")
               (:file "src/models/package")
               (:file "src/models/command-definition")
               (:file "src/models/tool-definition")
               (:file "src/models/session-state")
               (:file "src/models/execution-cycle")
               (:file "src/models/permission-decision")
               (:file "src/models/compatibility-fixture")
               (:file "src/session/package")
               (:file "src/session/serializer")
               (:file "src/session/store")
               (:file "src/tools/package")
               (:file "src/tools/echo-tool")
               (:file "src/tools/failing-tool")
               (:file "src/tools/registry")
               (:file "src/services/package")
               (:file "src/core/package")
               (:file "src/core/command-registry")
               (:file "src/core/execution-context")
               (:file "src/core/execution-engine")
               (:file "src/core/session-loop")
               (:file "src/services/permission-policy")
               (:file "src/services/permission-audit")
               (:file "src/services/fixture-loader")
               (:file "src/services/tool-selection")
               (:file "src/services/tool-runner")
               (:file "src/services/golden-regression")
               (:file "src/services/session-service")
               (:file "src/cli/argv")
               (:file "src/cli/help-command")
               (:file "src/cli/session-command")
               (:file "src/cli/session-resume-command")
               (:file "src/cli/run-command")
               (:file "src/cli/main")))

(asdf:defsystem "cl-cc/tests"
  :depends-on ("cl-cc" "fiveam")
  :serial t
  :components ((:file "tests/test-package")
               (:file "tests/contract/fixture-helpers")
               (:file "tests/unit/argv-parser-test")
               (:file "tests/unit/models-test")
               (:file "tests/unit/execution-cycle-test")
               (:file "tests/unit/command-dispatch-test")
               (:file "tests/unit/permission-policy-test")
               (:file "tests/unit/session-store-test")
               (:file "tests/unit/cli-output-test")
               (:file "tests/integration/session-start-test")
               (:file "tests/integration/session-resume-test")
               (:file "tests/integration/tool-execution-test")
               (:file "tests/contract/cli-help-contract-test")
               (:file "tests/contract/permission-contract-test")
               (:file "tests/contract/golden-regression-test")
               (:file "tests/contract/run-fixture-contract-test")
               (:file "tests/run-tests")))