;;;; tests/contract/cli-help-contract-test.lisp - CLI 帮助契约测试
(in-package :cl-cc/tests)

(def-suite cli-help-contract-test :in cl-cc-suite)

(in-suite cli-help-contract-test)

(defun %extract-generated-readme-section (contents)
  (let* ((start-marker "<!-- BEGIN GENERATED COMMAND REFERENCE -->")
         (end-marker "<!-- END GENERATED COMMAND REFERENCE -->")
         (start (search start-marker contents))
         (end (search end-marker contents)))
    (when (and start end)
      (string-trim '(#\Space #\Tab #\Newline #\Return)
                   (subseq contents
                           (+ start (length start-marker))
                           end)))))

(defun %normalize-line-endings (text)
  (remove #\Return text))

(defun %normalize-generated-block-lines (text)
  (remove-if (lambda (line) (string= line ""))
             (mapcar (lambda (line)
                       (string-right-trim '(#\Space #\Tab)
                                          (substitute #\Space #\Tab line)))
                     (uiop:split-string (%normalize-line-endings text) :separator '(#\Newline)))))

(test cli-help-output-contract
  (cl-cc.core:reset-command-registry)
  (let ((help-output (cl-cc:render-help)))
    (is (search "Usage:" help-output))
    (is (search "元信息命令:" help-output))
    (is (search "交互命令:" help-output))
    (is (search "会话命令:" help-output))
    (is (search "自动化命令:" help-output))
    (is (search "文档命令:" help-output))
    (is (search "help [--auth-scope <auth-scope>] [--group-scope <group-scope>]" help-output))
    (is (search "chat [<session-id-or-path>] [--session-path <session-path>] [--session-id <session-id>] [--tool <tool-id>]" help-output))
    (is (search "metadata: group=meta; source=builtin" help-output))
    (is (search "metadata: group=chat; source=builtin; requires-auth" help-output))
    (is (search "docs sync-reference [<output-path>] [--check] [--auth-scope <auth-scope>] [--group-scope <group-scope>] [--output-format <output-format>]" help-output))
    (is (search "metadata: group=docs; source=builtin" help-output))
    (is (search "run --fixture <fixture-id>... [--output-format <output-format>]" help-output))
    (is (search "metadata: group=automation; source=builtin; requires-auth" help-output))
    (is (search "session list [--session-dir <session-dir>] [--output-format <output-format>]" help-output))
    (is (search "session start [--session-id <session-id>] [--session-path <session-path>] [--history-index <history-index>] [--output-format <output-format>]" help-output))
    (is (search "session resume <session-id-or-path> [--output-format <output-format>]" help-output))
    (is (search "session run <session-id-or-path> [<user-input>] [--session-path <session-path>] [--tool <tool-id>] [--output-format <output-format>]" help-output))
    (is (search "metadata: group=session; source=builtin; requires-auth" help-output))
    (is (search "--auth-scope <auth-scope>  过滤帮助视图: all、public 或 requires-auth [default: all]" help-output))
    (is (search "--group-scope <group-scope>  过滤帮助分组视图: all、meta、chat、session、automation 或 docs [default: all]" help-output))
    (is (search "--check  仅检查命令参考是否需要同步，不写回文件" help-output))
    (is (search "--auth-scope <auth-scope>  生成或检查指定 auth 视图的命令参考: all、public 或 requires-auth [default: all]" help-output))
    (is (search "--group-scope <group-scope>  生成或检查指定命令分组视图: all、meta、chat、session、automation 或 docs [default: all]" help-output))
    (is (search "-o, --output-format <output-format>  指定输出格式: text 或 json [default: text]" help-output))
    (is (search "cl-cc --help" help-output))
    (is (search "cl-cc -h" help-output))
    (is (search "cl-cc help" help-output))
    (is (search "cl-cc c" help-output))
    (is (search "启动最小交互式会话 shell" help-output))
    (is (search "--session-dir <session-dir>  指定 session list 扫描的目录；未提供时使用默认会话目录" help-output))
    (is (search "-i, --session-id <session-id>  显式指定新会话 ID" help-output))
    (is (search "--session-path <session-path>  创建会话后立即将快照写入指定路径" help-output))
    (is (search "--history-index <history-index>  设置初始历史索引" help-output))
    (is (search "-o, --output-format <output-format>  指定输出格式: text 或 json [default: text]" help-output))
    (is (search "--pretty  以多行缩进格式输出 JSON [requires: --output-format=json] [conflicts: --compact]" help-output))
    (is (search "--compact  以紧凑单行格式输出 JSON [requires: --output-format=json] [conflicts: --pretty]" help-output))
    (is (search "-t, --tool <tool-id>  覆盖自动工具选择并按给定顺序执行 [repeatable]" help-output))))

(test generated-command-reference-contract
  (cl-cc.core:reset-command-registry)
  (let* ((readme (uiop:read-file-string "README.md"))
         (generated-block (%extract-generated-readme-section readme))
         (expected-block (string-trim '(#\Space #\Tab #\Newline #\Return)
                                      (cl-cc:render-command-reference-markdown))))
    (is (not (null generated-block)))
    (is (search "### 元信息命令" expected-block))
    (is (search "### 交互命令" expected-block))
    (is (search "### 会话命令" expected-block))
    (is (search "### 自动化命令" expected-block))
    (is (search "### 文档命令" expected-block))
    (is (search "- Usage: `cl-cc help [--auth-scope <auth-scope>] [--group-scope <group-scope>]`" expected-block))
    (is (search "- Options:" expected-block))
    (is (search "  - --auth-scope <auth-scope>  过滤帮助视图: all、public 或 requires-auth [default: all]" expected-block))
    (is (search "  - --group-scope <group-scope>  过滤帮助分组视图: all、meta、chat、session、automation 或 docs [default: all]" expected-block))
    (is (search "- Usage: `cl-cc docs sync-reference [<output-path>] [--check] [--auth-scope <auth-scope>] [--group-scope <group-scope>] [--output-format <output-format>]`" expected-block))
    (is (search "  - --auth-scope <auth-scope>  生成或检查指定 auth 视图的命令参考: all、public 或 requires-auth [default: all]" expected-block))
    (is (search "  - --group-scope <group-scope>  生成或检查指定命令分组视图: all、meta、chat、session、automation 或 docs [default: all]" expected-block))
    (is (search "- Metadata: `group=chat`, `source=builtin`, `requires-auth`" expected-block))
    (is (search "- Metadata: `group=docs`, `source=builtin`" expected-block))
    (is (search "- Metadata: `group=automation`, `source=builtin`, `requires-auth`" expected-block))
    (is (search "- Output Schema: `text`: result message; `json`: `path`, `status`, `checkOnly`, `updated`, `needsSync`, `durationSeconds`, `exitCode` [closed]" expected-block))
    (is (search "- JSON Fields:" expected-block))
    (is (search "  - `path`: 目标文档路径 [type: `string`]" expected-block))
    (is (search "  - `status`: 同步状态: synced、in-sync 或 drift [type: `string`] [allowed: `synced`, `in-sync`, `drift`]" expected-block))
    (is (search "  - `durationSeconds`: 本次 docs sync 执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "  - `exitCode`: 命令退出码 [type: `integer`] [min: `0`] [max: `255`]" expected-block))
    (is (search "#### `session list`" expected-block))
    (is (search "- Usage: `cl-cc session list [--session-dir <session-dir>] [--output-format <output-format>]`" expected-block))
    (is (search "- Metadata: `group=session`, `source=builtin`" expected-block))
    (is (search "- Metadata: `group=session`, `source=builtin`, `requires-auth`" expected-block))
    (is (search "- Output Schema: `text`: fixture execution summary; `json`: `status`, `fixtureCount`, `successfulCount`, `failedCount`, `durationSeconds`, `statusCounts`, `ok`, `exitCode`, `results` [closed]" expected-block))
    (is (search "  - `status`: 聚合结果状态 [type: `string`] [allowed-when-zero: `exitCode` => `success`] [allowed-when-nonzero: `exitCode` => `partial`, `failed`, `denied`, `not-found`] [allowed: `success`, `partial`, `failed`, `denied`, `not-found`]" expected-block))
    (is (search "  - `fixtureCount`: 本次执行的 fixture 数量 [type: `integer`] [min: `0`] [count-of: `results`] [sum-of: `statusCounts.success`, `statusCounts.failed`, `statusCounts.partial`, `statusCounts.denied`, `statusCounts.not-found`, `statusCounts.unknown`]" expected-block))
    (is (search "  - `successfulCount`: 成功 fixture 数量 [type: `integer`] [min: `0`] [matches: `statusCounts.success`]" expected-block))
    (is (search "  - `failedCount`: 失败 fixture 数量 [type: `integer`] [min: `0`] [matches: `statusCounts.failed`]" expected-block))
    (is (search "  - `durationSeconds`: 本次 run 聚合执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "  - `results`: 逐 fixture 的结果记录，包含稳定文本摘要与 toolResults [type: `array`] [min-items: `1`] [closed]" expected-block))
    (is (search "  - `statusCounts`: 各状态计数映射" expected-block))
    (is (search "  - `statusCounts`: 各状态计数映射 [type: `object`] [closed]" expected-block))
    (is (search "  - `ok`: 是否全部成功 [type: `boolean`] [true-when-zero: `exitCode`]" expected-block))
    (is (search "    - `success`: 成功 fixture 数量 [type: `integer`] [min: `0`] [matches-when: `status` = `success` => `fixtureCount`]" expected-block))
    (is (search "    - `failed`: 失败 fixture 数量 [type: `integer`] [min: `0`] [matches-when: `status` = `failed` => `fixtureCount`]" expected-block))
    (is (search "    - `partial`: 混合结果 fixture 数量" expected-block))
    (is (search "    - `denied`: 权限拒绝 fixture 数量 [type: `integer`] [min: `0`] [matches-when: `status` = `denied` => `fixtureCount`]" expected-block))
    (is (search "    - `not-found`: 工具未找到 fixture 数量 [type: `integer`] [min: `0`] [matches-when: `status` = `not-found` => `fixtureCount`]" expected-block))
    (is (search "    - `unknown`: 未归类 fixture 数量" expected-block))
    (is (search "  - `fixtureId`: fixture 标识 [type: `string`]" expected-block))
    (is (search "  - `status`: 该 fixture 的聚合状态" expected-block))
    (is (search "  - `durationSeconds`: 该 fixture 执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "  - `result`: 兼容既有 golden 的稳定文本摘要" expected-block))
    (is (search "  - `toolResults`: 逐工具尝试记录 [type: `array`] [min-items: `1`] [closed]" expected-block))
    (is (search "    - `toolId`: 工具标识" expected-block))
    (is (search "    - `status`: 该次工具尝试状态 [type: `string`] [allowed: `success`, `failed`, `denied`, `not-found`]" expected-block))
    (is (search "    - `durationSeconds`: 该次工具尝试执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "    - `output`: 按工具 output-schema 或 error-output-schema 派生的结构化输出，字段集合由工具定义直接提供 [type: `object`] [optional] [nullable] [closed]" expected-block))
    (is (search "      - `echo-tool.result`: 工具返回的回显结果 [type: `string`]" expected-block))
    (is (search "      - `failing-tool.error`: 失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `failing-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "      - `file-read-tool.result`: 文件读取结果内容 [type: `string`]" expected-block))
    (is (search "      - `file-read-tool.error`: 文件读取失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `file-read-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "      - `directory-list-tool.result`: 目录列举结果内容 [type: `string`]" expected-block))
    (is (search "      - `directory-list-tool.error`: 目录列举失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `directory-list-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "      - `grep-tool.result`: 搜索结果文本，每行一条匹配记录 [type: `string`]" expected-block))
    (is (search "      - `grep-tool.error`: 搜索失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `grep-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "      - `file-write-tool.result`: 文件写入结果摘要 [type: `string`]" expected-block))
    (is (search "      - `file-write-tool.error`: 文件写入失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `file-write-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "      - `file-edit-tool.result`: 文件编辑结果摘要 [type: `string`]" expected-block))
    (is (search "      - `file-edit-tool.path`: 本次编辑目标文件路径 [type: `string`]" expected-block))
    (is (search "      - `file-edit-tool.preview`: 是否为预览模式；普通写回路径下为 null [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "      - `file-edit-tool.matchCount`: 本次实际替换的命中数量 [type: `integer`] [min: `1`]" expected-block))
    (is (search "      - `file-edit-tool.totalMatches`: 旧文本在文件中的总匹配次数；指定 occurrence 时可大于 1 [type: `integer`] [min: `1`]" expected-block))
    (is (search "      - `file-edit-tool.selectedOccurrence`: 本次实际替换的命中序号（1-based）；replaceAll 模式下为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "      - `file-edit-tool.lineContext`: 本次生成 lineDiffPreview 时实际采用的上下文行数 [type: `integer`] [min: `0`]" expected-block))
    (is (search "      - `file-edit-tool.ignoreCase`: 本次匹配是否忽略大小写 [type: `boolean`]" expected-block))
    (is (search "      - `file-edit-tool.useRegex`: 本次匹配是否使用正则表达式 [type: `boolean`]" expected-block))
    (is (search "      - `file-edit-tool.matchStart`: 命中文本的起始字符偏移（0-based） [type: `integer`] [min: `0`]" expected-block))
    (is (search "      - `file-edit-tool.matchEnd`: 命中文本的结束字符偏移（exclusive） [type: `integer`] [min: `0`]" expected-block))
    (is (search "      - `file-edit-tool.matchStartLine`: 命中文本起始位置所在行号（1-based） [type: `integer`] [min: `1`]" expected-block))
    (is (search "      - `file-edit-tool.matchStartColumn`: 命中文本起始位置所在列号（1-based） [type: `integer`] [min: `1`]" expected-block))
    (is (search "      - `file-edit-tool.matchEndLine`: 命中文本结束位置所在行号（1-based，exclusive） [type: `integer`] [min: `1`]" expected-block))
    (is (search "      - `file-edit-tool.matchEndColumn`: 命中文本结束位置所在列号（1-based，exclusive） [type: `integer`] [min: `1`]" expected-block))
    (is (search "      - `file-edit-tool.matchedText`: 实际命中的原始文本片段 [type: `string`]" expected-block))
    (is (search "      - `file-edit-tool.replacementText`: 本次命中实际写入的新文本片段；正则模式下为捕获组展开后的结果 [type: `string`]" expected-block))
    (is (search "      - `file-edit-tool.beforePreview`: 替换前的局部预览片段 [type: `string`]" expected-block))
    (is (search "      - `file-edit-tool.afterPreview`: 替换后的局部预览片段 [type: `string`]" expected-block))
    (is (search "      - `file-edit-tool.diffPreview`: 替换前后合并展示的稳定 diff 预览片段 [type: `string`]" expected-block))
    (is (search "      - `file-edit-tool.lineDiffPreview`: 替换前后按行展示并带上下文的稳定 diff 预览片段 [type: `string`]" expected-block))
    (is (search "      - `file-edit-tool.unifiedDiffPreview`: 替换前后按 unified diff 风格展示的稳定预览片段 [type: `string`]" expected-block))
    (is (search "      - `file-edit-tool.writeApplied`: 是否已实际写回文件；preview 模式下为 null [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "      - `file-edit-tool.error`: 文件编辑失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `file-edit-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "    - `error`: 失败时的人类可读摘要，成功时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-tool.result`: shell 执行摘要 [type: `string`]" expected-block))
    (is (search "      - `shell-tool.command`: 本次执行的 shell 命令 [type: `string`]" expected-block))
    (is (search "      - `shell-tool.directory`: 本次命令实际执行目录 [type: `string`]" expected-block))
    (is (search "      - `shell-tool.background`: 本次执行是否以后台模式启动 [type: `boolean`]" expected-block))
    (is (search "      - `shell-tool.backgroundTaskId`: 后台任务标识；前台模式下为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-tool.outputPath`: 后台输出日志路径；前台模式下为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-tool.processId`: 底层进程 ID；不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-tool.stdout`: shell 标准输出文本；后台模式下为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-tool.stderr`: shell 标准错误文本；后台模式下为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-tool.exitCode`: shell 进程退出码；超时终止时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-tool.timedOut`: 本次执行是否因超时被终止 [type: `boolean`]" expected-block))
    (is (search "      - `shell-tool.error`: shell 执行失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `shell-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "      - `shell-task-list-tool.result`: 后台 shell 任务列表摘要 [type: `string`]" expected-block))
    (is (search "      - `shell-task-list-tool.statusFilter`: 本次任务列表实际应用的状态过滤器 [type: `string`]" expected-block))
    (is (search "      - `shell-task-list-tool.taskIdPrefixFilter`: 本次任务列表实际应用的任务 ID 前缀过滤器；未指定时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-list-tool.directoryContainsFilter`: 本次任务列表实际应用的目录片段过滤器；未指定时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-list-tool.terminationReasonFilter`: 本次任务列表实际应用的终止原因过滤器；未指定时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-list-tool.totalCount`: 当前后台任务总数 [type: `integer`] [min: `0`]" expected-block))
    (is (search "      - `shell-task-list-tool.runningCount`: 当前运行中的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "      - `shell-task-list-tool.stoppedCount`: 当前已停止的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "      - `shell-task-list-tool.completedCount`: 当前已完成的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "      - `shell-task-list-tool.failedCount`: 当前失败的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "      - `shell-task-list-tool.tasks`: 后台任务列表，每项包含 taskId、status、stallDetected、terminationReason、endedAt、command 等字段 [type: `array`]" expected-block))
    (is (search "      - `shell-task-list-tool.error`: 后台 shell 任务列表失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `shell-task-list-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "      - `shell-task-detail-tool.result`: 后台 shell 任务详情摘要 [type: `string`]" expected-block))
    (is (search "      - `shell-task-detail-tool.taskId`: 后台任务标识 [type: `string`]" expected-block))
    (is (search "      - `shell-task-detail-tool.status`: 后台任务当前状态 [type: `string`]" expected-block))
    (is (search "      - `shell-task-detail-tool.running`: 后台任务当前是否仍在运行 [type: `boolean`]" expected-block))
    (is (search "      - `shell-task-detail-tool.stopped`: 后台任务是否被显式停止 [type: `boolean`]" expected-block))
    (is (search "      - `shell-task-detail-tool.command`: 后台任务对应的 shell 命令 [type: `string`]" expected-block))
    (is (search "      - `shell-task-detail-tool.directory`: 后台任务的执行目录 [type: `string`]" expected-block))
    (is (search "      - `shell-task-detail-tool.outputPath`: 后台任务输出日志路径 [type: `string`]" expected-block))
    (is (search "      - `shell-task-detail-tool.processId`: 后台任务底层进程 ID；不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.exitCode`: 后台任务退出码；运行中或不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.stallDetected`: 后台任务是否疑似卡在交互提示；未检测到时为 false [type: `boolean`]" expected-block))
    (is (search "      - `shell-task-detail-tool.stallDetectedAt`: 后台任务首次检测到疑似卡住的时间，UTC ISO-8601 格式；未检测到时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.stallPromptLine`: 后台任务触发 stall 检测时的最后一行输出；未检测到时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.startedAt`: 后台任务开始时间，UTC ISO-8601 格式 [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.stoppedAt`: 后台任务被显式停止的时间，未停止时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.finishedAt`: 后台任务自然结束时间，运行中或显式停止时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.terminationReason`: 后台任务终止原因；运行中时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.endedAt`: 后台任务终止时间，UTC ISO-8601 格式；运行中时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.durationSeconds`: 后台任务已运行或总运行时长（秒） [type: `number`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.outputBytes`: 后台任务当前输出日志字节数；日志不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.outputLineCount`: 后台任务当前输出日志行数；日志不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.outputUpdatedAt`: 后台任务输出日志最后更新时间，UTC ISO-8601 格式；日志不可用时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-detail-tool.error`: 后台 shell 任务详情失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `shell-task-detail-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "      - `shell-task-cleanup-tool.result`: 后台 shell 任务清理摘要 [type: `string`]" expected-block))
    (is (search "      - `shell-task-cleanup-tool.statusFilter`: 本次清理实际应用的状态过滤器 [type: `string`]" expected-block))
    (is (search "      - `shell-task-cleanup-tool.terminationReasonFilter`: 本次清理实际应用的终止原因过滤器；未指定时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-cleanup-tool.removedCount`: 本次清理移除的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "      - `shell-task-cleanup-tool.remainingCount`: 清理完成后注册表中剩余的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "      - `shell-task-cleanup-tool.removedTaskIds`: 本次清理移除的后台任务 ID 列表 [type: `array`]" expected-block))
    (is (search "      - `shell-task-cleanup-tool.error`: 后台 shell 任务清理失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `shell-task-cleanup-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "      - `shell-task-tool.result`: 后台 shell 任务摘要 [type: `string`]" expected-block))
    (is (search "      - `shell-task-tool.taskId`: 单任务模式下的后台任务标识；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.taskIds`: 批量模式下的后台任务标识列表；单任务模式为 null [type: `array`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.taskCount`: 本次操作覆盖的后台任务数量；单任务模式为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.action`: 本次执行的任务动作 [type: `string`]" expected-block))
    (is (search "      - `shell-task-tool.status`: 后台任务当前状态；批量模式下为聚合状态，相异时为 mixed [type: `string`]" expected-block))
    (is (search "      - `shell-task-tool.running`: 后台任务当前是否仍在运行；批量模式下表示是否仍有任务在运行 [type: `boolean`]" expected-block))
    (is (search "      - `shell-task-tool.stopped`: 后台任务是否被显式停止；批量模式下表示是否全部已停止 [type: `boolean`]" expected-block))
    (is (search "      - `shell-task-tool.command`: 单任务模式下后台任务对应的 shell 命令；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.directory`: 单任务模式下后台任务的执行目录；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.outputPath`: 单任务模式下后台任务输出日志路径；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.processId`: 后台任务底层进程 ID；不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.exitCode`: 后台任务退出码；运行中或不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.stallDetected`: 后台任务是否疑似卡在交互提示；未检测到时为 false [type: `boolean`]" expected-block))
    (is (search "      - `shell-task-tool.stallDetectedAt`: 后台任务首次检测到疑似卡住的时间，UTC ISO-8601 格式；未检测到时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.stallPromptLine`: 后台任务触发 stall 检测时的最后一行输出；未检测到时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.terminationReason`: 后台任务终止原因；运行中时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.endedAt`: 后台任务终止时间，UTC ISO-8601 格式；运行中时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.runningCount`: 批量模式下仍在运行的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.stoppedCount`: 批量模式下已停止的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.completedCount`: 批量模式下已完成的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.failedCount`: 批量模式下已失败的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-tool.tasks`: 批量模式下的逐任务结果数组；单任务模式为 null [type: `array`] [optional] [nullable] [closed]" expected-block))
    (is (search "      - `shell-task-tool.timedOut`: 本次 wait 是否因达到 timeoutSeconds 而提前返回；非 wait 动作为 false [type: `boolean`]" expected-block))
    (is (search "      - `shell-task-tool.error`: 后台 shell 任务失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `shell-task-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "      - `shell-task-output-tool.result`: 后台任务输出读取摘要 [type: `string`]" expected-block))
    (is (search "      - `shell-task-output-tool.taskId`: 单任务模式下的后台任务标识；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.taskIds`: 批量模式下的后台任务标识数组；单任务模式为 null [type: `array`] [optional] [nullable] [closed]" expected-block))
    (is (search "      - `shell-task-output-tool.taskCount`: 批量模式下的后台任务数量；单任务模式为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.mode`: 本次输出读取模式：tail、range 或 mixed [type: `string`]" expected-block))
    (is (search "      - `shell-task-output-tool.status`: 后台任务当前状态；批量模式下若存在多种状态则为 mixed [type: `string`]" expected-block))
    (is (search "      - `shell-task-output-tool.running`: 后台任务当前是否仍在运行；批量模式下表示是否仍有任一任务运行 [type: `boolean`]" expected-block))
    (is (search "      - `shell-task-output-tool.stopped`: 后台任务是否被显式停止；批量模式下表示是否全部已停止 [type: `boolean`]" expected-block))
    (is (search "      - `shell-task-output-tool.outputPath`: 单任务模式下后台任务输出日志路径；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.linesRequested`: 共享请求下的输出窗口行数；按任务定制且不一致时为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.requestedStartLine`: 本次请求的起始行号；tail 模式下为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.requestedEndLine`: 本次请求的结束行号；tail 模式下为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.followSeconds`: 本次请求的 follow 秒数；未指定时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.waitUntilFinished`: 共享请求是否阻塞直到后台任务结束；按任务定制且不一致时为 null [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.startLine`: 单任务模式下本次返回内容的起始行号；无内容或批量模式时为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.endLine`: 单任务模式下本次返回内容的结束行号；无内容或批量模式时为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.totalLines`: 单任务模式下当前后台输出日志总行数；批量模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.runningCount`: 批量模式下仍在运行的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.stoppedCount`: 批量模式下已停止的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.completedCount`: 批量模式下已完成的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.failedCount`: 批量模式下已失败的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.tasks`: 批量模式下的逐任务输出结果数组；单任务模式为 null [type: `array`] [optional] [nullable] [closed]" expected-block))
    (is (search "      - `shell-task-output-tool.content`: 单任务模式下按绝对行号编号后的输出内容；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "      - `shell-task-output-tool.error`: 后台 shell 任务输出失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `shell-task-output-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "    - `errorCode`: 稳定错误码，成功时为 null [type: `string`] [allowed: `FAIL`, `PERMISSION-DENIED`, `TOOL-NOT-FOUND`, `FILE-READ-FAILED`, `DIRECTORY-LIST-FAILED`, `FILE-WRITE-FAILED`, `FILE-EDIT-FAILED`, `GREP-SEARCH-FAILED`, `TODO-WRITE-FAILED`, `SHELL-EXECUTION-FAILED`] [optional] [nullable]" expected-block))
    (is (search "- Output Schema: `text`: session start message; `json`: `status`, `sessionId`, `historyIndex`, `sessionStatus`, `tasks`, `todoList`, `sessionPath`, `saved`, `durationSeconds`, `exitCode` [closed]" expected-block))
    (is (search "  - `sessionId`: 新会话 ID [type: `string`]" expected-block))
    (is (search "  - `status`: 结果状态，当前固定为 success [type: `string`] [allowed: `success`]" expected-block))
    (is (search "  - `historyIndex`: 初始历史索引，未指定时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `sessionStatus`: 会话状态，当前通常为 active [type: `string`] [allowed: `active`] [optional] [nullable]" expected-block))
    (is (search "  - `tasks`: 当前会话已知的后台任务快照列表；无任务时该字段可省略 [type: `array`] [optional] [closed]" expected-block))
    (is (search "  - `sessionPath`: 若请求持久化，则为写入的快照路径 [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `saved`: 是否已将新会话快照写入 sessionPath [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `durationSeconds`: 本次 session start 执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "  - `exitCode`: 命令退出码 [type: `integer`] [min: `0`] [max: `255`]" expected-block))
    (is (search "- Output Schema: `text`: session resume message; `json`: `status`, `sessionId`, `historyIndex`, `sessionStatus`, `tasks`, `todoList`, `durationSeconds`, `exitCode` [closed]" expected-block))
    (is (search "  - `historyIndex`: 恢复快照中的历史索引，缺失时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `sessionStatus`: 恢复后的会话状态 [type: `string`] [allowed: `active`] [optional] [nullable]" expected-block))
    (is (search "  - `tasks`: 当前会话已知的后台任务快照列表；无任务时该字段可省略 [type: `array`] [optional] [closed]" expected-block))
    (is (search "  - `durationSeconds`: 本次 session resume 执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "  - `exitCode`: 命令退出码 [type: `integer`] [min: `0`] [max: `255`]" expected-block))
    (is (search "- Usage: `cl-cc session run <session-id-or-path> [<user-input>] [--session-path <session-path>] [--tool <tool-id>] [--output-format <output-format>]`" expected-block))
    (is (search "- Output Schema: `text`: session run message; `json`: `status`, `sessionId`, `historyIndex`, `sessionStatus`, `tasks`, `todoList`, `input`, `executionStatus`, `selectedTools`, `executionPlan`, `gitRoot`, `gitBranch`, `gitDirty`, `gitStatusLines`, `gitRecentCommits`, `result`, `toolResults`, `sessionPath`, `saved`, `durationSeconds`, `exitCode` [closed]" expected-block))
    (is (search "  - `tasks`: 当前会话已知的后台任务快照列表；无任务时该字段可省略 [type: `array`] [optional] [closed]" expected-block))
    (is (search "  - `input`: 本次 session run 实际使用的用户输入，缺失时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `executionStatus`: 本次 session run 的执行状态 [type: `string`] [allowed: `success`, `failed`]" expected-block))
    (is (search "  - `selectedTools`: 本次 session run 最终采用的工具顺序 [type: `array`] [min-items: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `executionPlan`: 本次 session run 的归一化执行计划，包含每步工具与输入 [type: `array`] [min-items: `1`] [optional] [nullable] [closed]" expected-block))
    (is (search "    - `tool`: 计划步骤对应的工具标识 [type: `string`]" expected-block))
    (is (search "    - `input`: 计划步骤归一化后的工具输入 [optional] [nullable]" expected-block))
    (is (search "  - `gitRoot`: 本次 session run 检测到的 Git 根目录；未处于 Git 仓库时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `gitBranch`: 本次 session run 检测到的 Git 当前分支；无法识别时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `gitDirty`: 当前 Git 工作树是否存在未提交改动；未处于 Git 仓库时为 null [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `gitStatusLines`: `git status --short` 的逐行快照；仓库干净时为空数组，未处于 Git 仓库时为 null [type: `array`] [optional] [nullable]" expected-block))
    (is (search "  - `gitRecentCommits`: 最近的 Git commit 摘要列表；未处于 Git 仓库时为 null [type: `array`] [optional] [nullable]" expected-block))
    (is (search "  - `result`: 本次 session run 的稳定文本执行结果 [type: `string`]" expected-block))
    (is (search "  - `toolResults`: 本次 session run 的逐工具尝试记录 [type: `array`] [min-items: `1`] [closed]" expected-block))
    (is (search "  - -t, --tool <tool-id>  覆盖自动工具选择并按给定顺序执行 [repeatable]" expected-block))
    (is (search "## 工具参考" expected-block))
    (is (search "### `echo-tool`" expected-block))
    (is (search "- Input Schema: `text`: input string; `json`: `input` [closed]" expected-block))
    (is (search "- Input JSON Fields:" expected-block))
    (is (search "  - `input`: 待回显的输入字符串 [type: `string`]" expected-block))
    (is (search "- Output Schema: `text`: echoed string; `json`: `result` [closed]" expected-block))
    (is (search "- Output JSON Fields:" expected-block))
    (is (search "  - `result`: 工具返回的回显结果 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `default`" expected-block))
    (is (search "### `failing-tool`" expected-block))
    (is (search "- Input Schema: `text`: input string; `json`: `input` [closed]" expected-block))
    (is (search "  - `input`: 触发失败路径的输入字符串 [type: `string`]" expected-block))
    (is (search "- Output Schema: `text`: no successful output" expected-block))
    (is (search "- Error Output Schema: `text`: failed output; `json`: `error`, `code` [closed]" expected-block))
    (is (search "- Error JSON Fields:" expected-block))
    (is (search "  - `error`: 失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Failure Modes: `failed`" expected-block))
    (is (search "### `file-edit-tool`" expected-block))
    (is (search "- Input Schema: `text`: edit request; `json`: `path`, `oldText`, `newText`, `occurrence`, `replaceAll`, `lineContext`, `ignoreCase`, `useRegex`, `multiline`, `dotAll`, `wholeWord`, `leftWordBoundary`, `rightWordBoundary`, `preview` [closed]" expected-block))
    (is (search "  - `path`: 待编辑的文件路径 [type: `string`]" expected-block))
    (is (search "  - `oldText`: 期望被替换的原始文本；默认按精确文本匹配，useRegex 为 true 时按正则表达式解释 [type: `string`]" expected-block))
    (is (search "  - `newText`: 替换后的新文本，可为空字符串；useRegex 为 true 时支持 `$1` / `\\1` 形式的捕获组引用 [type: `string`]" expected-block))
    (is (search "  - `occurrence`: 当旧文本出现多次时，指定要替换的第几处命中（1-based） [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `replaceAll`: 是否替换全部命中；与 occurrence 互斥，缺省为 false [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `lineContext`: 生成 lineDiffPreview 时保留的上下文行数，缺省为 1 [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `ignoreCase`: 是否忽略大小写；缺省为 false [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `useRegex`: 是否将 oldText 作为正则表达式解释；缺省为 false [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `multiline`: 是否启用正则多行模式（^/$ 按行匹配）；缺省为 false [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `dotAll`: 是否启用正则 dotAll 模式（`.` 可跨换行匹配）；缺省为 false [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `wholeWord`: 是否要求左右两侧都为单词边界；缺省为 false [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `leftWordBoundary`: 是否要求命中左侧为单词边界；缺省为 false [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `rightWordBoundary`: 是否要求命中右侧为单词边界；缺省为 false [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `preview`: 是否只预览替换摘要而不落盘，缺省为 false [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `result`: 文件编辑结果摘要 [type: `string`]" expected-block))
    (is (search "  - `path`: 本次编辑目标文件路径 [type: `string`]" expected-block))
    (is (search "  - `preview`: 是否为预览模式；普通写回路径下为 null [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `matchCount`: 本次实际替换的命中数量 [type: `integer`] [min: `1`]" expected-block))
    (is (search "  - `totalMatches`: 旧文本在文件中的总匹配次数；指定 occurrence 时可大于 1 [type: `integer`] [min: `1`]" expected-block))
    (is (search "  - `selectedOccurrence`: 本次实际替换的命中序号（1-based）；replaceAll 模式下为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `lineContext`: 本次生成 lineDiffPreview 时实际采用的上下文行数 [type: `integer`] [min: `0`]" expected-block))
    (is (search "  - `ignoreCase`: 本次匹配是否忽略大小写 [type: `boolean`]" expected-block))
    (is (search "  - `useRegex`: 本次匹配是否使用正则表达式 [type: `boolean`]" expected-block))
    (is (search "  - `multiline`: 本次匹配是否启用正则多行模式 [type: `boolean`]" expected-block))
    (is (search "  - `dotAll`: 本次匹配是否启用正则 dotAll 模式 [type: `boolean`]" expected-block))
    (is (search "  - `wholeWord`: 本次匹配是否要求左右两侧都为单词边界 [type: `boolean`]" expected-block))
    (is (search "  - `leftWordBoundary`: 本次匹配是否要求左侧为单词边界 [type: `boolean`]" expected-block))
    (is (search "  - `rightWordBoundary`: 本次匹配是否要求右侧为单词边界 [type: `boolean`]" expected-block))
    (is (search "  - `matchStart`: 命中文本的起始字符偏移（0-based） [type: `integer`] [min: `0`]" expected-block))
    (is (search "  - `matchEnd`: 命中文本的结束字符偏移（exclusive） [type: `integer`] [min: `0`]" expected-block))
    (is (search "  - `matchStartLine`: 命中文本起始位置所在行号（1-based） [type: `integer`] [min: `1`]" expected-block))
    (is (search "  - `matchStartColumn`: 命中文本起始位置所在列号（1-based） [type: `integer`] [min: `1`]" expected-block))
    (is (search "  - `matchEndLine`: 命中文本结束位置所在行号（1-based，exclusive） [type: `integer`] [min: `1`]" expected-block))
    (is (search "  - `matchEndColumn`: 命中文本结束位置所在列号（1-based，exclusive） [type: `integer`] [min: `1`]" expected-block))
    (is (search "  - `matchedText`: 实际命中的原始文本片段 [type: `string`]" expected-block))
    (is (search "  - `replacementText`: 本次命中实际写入的新文本片段；正则模式下为捕获组展开后的结果 [type: `string`]" expected-block))
    (is (search "  - `beforePreview`: 替换前的局部预览片段 [type: `string`]" expected-block))
    (is (search "  - `afterPreview`: 替换后的局部预览片段 [type: `string`]" expected-block))
    (is (search "  - `diffPreview`: 替换前后合并展示的稳定 diff 预览片段 [type: `string`]" expected-block))
    (is (search "  - `lineDiffPreview`: 替换前后按行展示并带上下文的稳定 diff 预览片段 [type: `string`]" expected-block))
    (is (search "  - `unifiedDiffPreview`: 替换前后按 unified diff 风格展示的稳定预览片段 [type: `string`]" expected-block))
    (is (search "  - `writeApplied`: 是否已实际写回文件；preview 模式下为 null [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `error`: 文件编辑失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `file-write`" expected-block))
    (is (search "### `file-read-tool`" expected-block))
    (is (search "- Input Schema: `text`: path string with optional line range(s); `json`: `path`, `startLine`, `endLine`, `contextLines`, `ranges` [closed]" expected-block))
    (is (search "  - `path`: 待读取的文件路径 [type: `string`]" expected-block))
    (is (search "  - `startLine`: 起始行号，缺省时读取整个文件 [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `endLine`: 结束行号，缺省时等于 startLine [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `contextLines`: 为所选行范围额外扩展的上下文行数；提供时会对扩展后重叠或相邻的 ranges 做稳定合并 [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `ranges`: 多段行范围列表；提供时按给定顺序拼接输出且自动去重重复行 [type: `array`] [optional] [nullable] [closed]" expected-block))
    (is (search "    - `startLine`: 行范围起始行号 [type: `integer`] [min: `1`]" expected-block))
    (is (search "    - `endLine`: 行范围结束行号 [type: `integer`] [min: `1`]" expected-block))
    (is (search "  - `result`: 文件读取结果内容 [type: `string`]" expected-block))
    (is (search "  - `error`: 文件读取失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `file-read`" expected-block))
    (is (search "### `directory-list-tool`" expected-block))
    (is (search "- Input Schema: `text`: path string with optional recursive/depth/contains modifiers; `json`: `path`, `recursive`, `depth`, `contains` [closed]" expected-block))
    (is (search "  - `path`: 待列举的目录路径 [type: `string`]" expected-block))
    (is (search "  - `recursive`: 是否递归列举子目录，缺省为 false [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `depth`: 递归列举的最大深度，缺省为不限制 [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `contains`: 仅返回路径中包含该子串的条目，缺省为不过滤 [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `result`: 目录列举结果内容 [type: `string`]" expected-block))
    (is (search "  - `error`: 目录列举失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `file-read`" expected-block))
    (is (search "### `grep-tool`" expected-block))
    (is (search "- Input Schema: `text`: search query, `query-1 || query-2`, or `query :: root`; `json`: `query`, `queries`, `root` [closed]" expected-block))
    (is (search "  - `query`: 待搜索的单个文本关键词 [type: `string`]" expected-block))
    (is (search "  - `queries`: 待搜索的多个文本关键词列表，任一命中即返回该行 [type: `array`] [optional] [nullable]" expected-block))
    (is (search "    - `query`: 待搜索的文本关键词 [type: `string`]" expected-block))
    (is (search "  - `root`: 搜索根路径，缺省为当前工作目录 [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `result`: 搜索结果文本，每行一条匹配记录 [type: `string`]" expected-block))
    (is (search "  - `error`: 搜索失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `file-read`" expected-block))
    (is (search "### `file-write-tool`" expected-block))
    (is (search "  - `path`: 待写入的文件路径 [type: `string`]" expected-block))
    (is (search "  - `content`: 待写入的文本内容 [type: `string`]" expected-block))
    (is (search "  - `result`: 文件写入结果摘要 [type: `string`]" expected-block))
    (is (search "  - `error`: 文件写入失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `file-write`" expected-block))
    (is (search "### `shell-tool`" expected-block))
    (is (search "- Input Schema: `text`: shell command request; `json`: `command`, `directory`, `background`, `timeoutSeconds` [closed]" expected-block))
    (is (search "  - `command`: 待执行的 shell 命令字符串 [type: `string`]" expected-block))
    (is (search "  - `directory`: 命令执行目录，缺省为当前工作目录 [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `background`: 是否以后台模式启动命令；缺省为 false [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `timeoutSeconds`: 超时时间（秒），缺省为不设超时 [type: `number`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `result`: shell 执行摘要 [type: `string`]" expected-block))
    (is (search "  - `background`: 本次执行是否以后台模式启动 [type: `boolean`]" expected-block))
    (is (search "  - `backgroundTaskId`: 后台任务标识；前台模式下为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `outputPath`: 后台输出日志路径；前台模式下为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `processId`: 底层进程 ID；不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `stdout`: shell 标准输出文本；后台模式下为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `stderr`: shell 标准错误文本；后台模式下为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `exitCode`: shell 进程退出码；超时终止时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `timedOut`: 本次执行是否因超时被终止 [type: `boolean`]" expected-block))
    (is (search "  - `error`: shell 执行失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `shell`" expected-block))
    (is (search "### `shell-task-list-tool`" expected-block))
    (is (search "- Input Schema: `text`: shell task list request; `json`: `all`, `status`, `taskIdPrefix`, `directoryContains`, `terminationReason` [closed]" expected-block))
    (is (search "  - `all`: 是否列出全部后台任务，当前缺省且固定为 true [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `status`: 按状态过滤后台任务，缺省为 all [type: `string`] [allowed: `all`, `running`, `stopped`, `completed`, `failed`] [optional] [nullable]" expected-block))
    (is (search "  - `taskIdPrefix`: 按任务 ID 前缀过滤后台任务 [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `directoryContains`: 按执行目录包含指定片段过滤后台任务 [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `terminationReason`: 按后台任务终止原因过滤，支持 exit、error-exit、stop、interrupt [type: `string`] [allowed: `exit`, `error-exit`, `stop`, `interrupt`] [optional] [nullable]" expected-block))
    (is (search "- Output Schema: `text`: shell task list result; `json`: `result`, `statusFilter`, `taskIdPrefixFilter`, `directoryContainsFilter`, `terminationReasonFilter`, `totalCount`, `runningCount`, `stoppedCount`, `completedCount`, `failedCount`, `tasks` [closed]" expected-block))
    (is (search "  - `result`: 后台 shell 任务列表摘要 [type: `string`]" expected-block))
    (is (search "  - `statusFilter`: 本次任务列表实际应用的状态过滤器 [type: `string`]" expected-block))
    (is (search "  - `taskIdPrefixFilter`: 本次任务列表实际应用的任务 ID 前缀过滤器；未指定时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `directoryContainsFilter`: 本次任务列表实际应用的目录片段过滤器；未指定时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `terminationReasonFilter`: 本次任务列表实际应用的终止原因过滤器；未指定时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `totalCount`: 当前后台任务总数 [type: `integer`] [min: `0`]" expected-block))
    (is (search "  - `runningCount`: 当前运行中的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "  - `stoppedCount`: 当前已停止的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "  - `completedCount`: 当前已完成的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "  - `failedCount`: 当前失败的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "  - `tasks`: 后台任务列表，每项包含 taskId、status、stallDetected、terminationReason、endedAt、command 等字段 [type: `array`]" expected-block))
    (is (search "- Error Output Schema: `text`: shell task list failed output; `json`: `error`, `code` [closed]" expected-block))
    (is (search "  - `error`: 后台 shell 任务列表失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `shell`" expected-block))
    (is (search "### `shell-task-detail-tool`" expected-block))
    (is (search "- Input Schema: `text`: shell task detail request; `json`: `taskId` [closed]" expected-block))
    (is (search "  - `taskId`: 后台任务标识 [type: `string`]" expected-block))
    (is (search "- Output Schema: `text`: shell task detail result; `json`: `result`, `taskId`, `status`, `running`, `stopped`, `command`, `directory`, `outputPath`, `processId`, `exitCode`, `stallDetected`, `stallDetectedAt`, `stallPromptLine`, `startedAt`, `stoppedAt`, `finishedAt`, `terminationReason`, `endedAt`, `durationSeconds`, `outputBytes`, `outputLineCount`, `outputUpdatedAt` [closed]" expected-block))
    (is (search "  - `result`: 后台 shell 任务详情摘要 [type: `string`]" expected-block))
    (is (search "  - `status`: 后台任务当前状态 [type: `string`]" expected-block))
    (is (search "  - `running`: 后台任务当前是否仍在运行 [type: `boolean`]" expected-block))
    (is (search "  - `stopped`: 后台任务是否被显式停止 [type: `boolean`]" expected-block))
    (is (search "  - `command`: 后台任务对应的 shell 命令 [type: `string`]" expected-block))
    (is (search "  - `directory`: 后台任务的执行目录 [type: `string`]" expected-block))
    (is (search "  - `outputPath`: 后台任务输出日志路径 [type: `string`]" expected-block))
    (is (search "  - `processId`: 后台任务底层进程 ID；不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `exitCode`: 后台任务退出码；运行中或不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `startedAt`: 后台任务开始时间，UTC ISO-8601 格式 [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `stoppedAt`: 后台任务被显式停止的时间，未停止时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `finishedAt`: 后台任务自然结束时间，运行中或显式停止时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `terminationReason`: 后台任务终止原因；运行中时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `endedAt`: 后台任务终止时间，UTC ISO-8601 格式；运行中时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `durationSeconds`: 后台任务已运行或总运行时长（秒） [type: `number`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "- Error Output Schema: `text`: shell task detail failed output; `json`: `error`, `code` [closed]" expected-block))
    (is (search "  - `error`: 后台 shell 任务详情失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `shell`" expected-block))
    (is (search "### `shell-task-cleanup-tool`" expected-block))
    (is (search "- Input Schema: `text`: shell task cleanup request; `json`: `status`, `terminationReason` [closed]" expected-block))
    (is (search "  - `status`: 按状态清理后台任务，缺省为 all（即 stopped/completed/failed） [type: `string`] [allowed: `all`, `stopped`, `completed`, `failed`] [optional] [nullable]" expected-block))
    (is (search "  - `terminationReason`: 按后台任务终止原因清理，支持 exit、error-exit、stop、interrupt [type: `string`] [allowed: `exit`, `error-exit`, `stop`, `interrupt`] [optional] [nullable]" expected-block))
    (is (search "- Output Schema: `text`: shell task cleanup result; `json`: `result`, `statusFilter`, `terminationReasonFilter`, `removedCount`, `remainingCount`, `removedTaskIds` [closed]" expected-block))
    (is (search "  - `result`: 后台 shell 任务清理摘要 [type: `string`]" expected-block))
    (is (search "  - `statusFilter`: 本次清理实际应用的状态过滤器 [type: `string`]" expected-block))
    (is (search "  - `terminationReasonFilter`: 本次清理实际应用的终止原因过滤器；未指定时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `removedCount`: 本次清理移除的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "  - `remainingCount`: 清理完成后注册表中剩余的后台任务数量 [type: `integer`] [min: `0`]" expected-block))
    (is (search "  - `removedTaskIds`: 本次清理移除的后台任务 ID 列表 [type: `array`]" expected-block))
    (is (search "- Error Output Schema: `text`: shell task cleanup failed output; `json`: `error`, `code` [closed]" expected-block))
    (is (search "  - `error`: 后台 shell 任务清理失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `shell`" expected-block))
    (is (search "### `shell-task-tool`" expected-block))
    (is (search "- Input Schema: `text`: shell task request; `json`: `taskId`, `taskIds`, `action`, `timeoutSeconds` [closed]" expected-block))
    (is (search "  - `taskId`: 单个后台任务标识；与 taskIds 二选一 [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `taskIds`: 批量 interrupt/stop/wait 的后台任务标识列表；与 taskId 二选一 [type: `array`] [optional] [nullable]" expected-block))
    (is (search "  - `action`: 动作类型，缺省为 status [type: `string`] [allowed: `status`, `interrupt`, `stop`, `wait`] [optional] [nullable]" expected-block))
    (is (search "  - `timeoutSeconds`: wait 动作的最长等待时间（秒），缺省为一直等待直到任务结束 [type: `number`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "- Output Schema: `text`: shell task result; `json`: `result`, `taskId`, `taskIds`, `taskCount`, `action`, `status`, `running`, `stopped`, `command`, `directory`, `outputPath`, `processId`, `exitCode`, `stallDetected`, `stallDetectedAt`, `stallPromptLine`, `terminationReason`, `endedAt`, `runningCount`, `stoppedCount`, `completedCount`, `failedCount`, `tasks`, `timedOut` [closed]" expected-block))
    (is (search "  - `result`: 后台 shell 任务摘要 [type: `string`]" expected-block))
    (is (search "  - `taskId`: 单任务模式下的后台任务标识；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `taskIds`: 批量模式下的后台任务标识列表；单任务模式为 null [type: `array`] [optional] [nullable]" expected-block))
    (is (search "  - `taskCount`: 本次操作覆盖的后台任务数量；单任务模式为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `status`: 后台任务当前状态；批量模式下为聚合状态，相异时为 mixed [type: `string`]" expected-block))
    (is (search "  - `running`: 后台任务当前是否仍在运行；批量模式下表示是否仍有任务在运行 [type: `boolean`]" expected-block))
    (is (search "  - `stopped`: 后台任务是否被显式停止；批量模式下表示是否全部已停止 [type: `boolean`]" expected-block))
    (is (search "  - `command`: 单任务模式下后台任务对应的 shell 命令；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `directory`: 单任务模式下后台任务的执行目录；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `outputPath`: 单任务模式下后台任务输出日志路径；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `processId`: 后台任务底层进程 ID；不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `exitCode`: 后台任务退出码；运行中或不可用时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `terminationReason`: 后台任务终止原因；运行中时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `endedAt`: 后台任务终止时间，UTC ISO-8601 格式；运行中时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `runningCount`: 批量模式下仍在运行的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `stoppedCount`: 批量模式下已停止的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `completedCount`: 批量模式下已完成的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `failedCount`: 批量模式下已失败的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `tasks`: 批量模式下的逐任务结果数组；单任务模式为 null [type: `array`] [optional] [nullable]" expected-block))
    (is (search "  - `timedOut`: 本次 wait 是否因达到 timeoutSeconds 而提前返回；非 wait 动作为 false [type: `boolean`]" expected-block))
    (is (search "  - `error`: 后台 shell 任务失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `shell`" expected-block))
    (is (search "### `shell-task-output-tool`" expected-block))
    (is (search "- Input Schema: `text`: shell task output request; `json`: `taskId`, `taskIds`, `tasks`, `lines`, `startLine`, `endLine`, `followSeconds`, `waitUntilFinished` [closed]" expected-block))
    (is (search "  - `taskId`: 单任务模式下的后台任务标识；与 taskIds 二选一，批量模式可为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `taskIds`: 批量模式下的后台任务标识数组；单任务模式为 null [type: `array`] [optional] [nullable] [closed]" expected-block))
    (is (search "  - `tasks`: 按任务定制批量输出请求的对象数组；与 taskId/taskIds 互斥，单任务模式为 null [type: `array`] [optional] [nullable] [closed]" expected-block))
    (is (search "  - `lines`: 待读取的输出行数；tail 模式下缺省为 20 [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `startLine`: 区间读取的起始行号；指定后进入 range 模式 [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `endLine`: 区间读取的结束行号；与 startLine 配套使用 [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `followSeconds`: 继续跟随日志输出的秒数；未指定时不 follow [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `waitUntilFinished`: 是否阻塞直到后台任务结束；与 followSeconds 互斥 [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "- Output Schema: `text`: shell task output result; `json`: `result`, `taskId`, `taskIds`, `taskCount`, `mode`, `status`, `running`, `stopped`, `outputPath`, `linesRequested`, `requestedStartLine`, `requestedEndLine`, `followSeconds`, `waitUntilFinished`, `startLine`, `endLine`, `totalLines`, `runningCount`, `stoppedCount`, `completedCount`, `failedCount`, `tasks`, `content` [closed]" expected-block))
    (is (search "  - `result`: 后台任务输出读取摘要 [type: `string`]" expected-block))
    (is (search "  - `taskId`: 单任务模式下的后台任务标识；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `taskIds`: 批量模式下的后台任务标识数组；单任务模式为 null [type: `array`] [optional] [nullable] [closed]" expected-block))
    (is (search "  - `taskCount`: 批量模式下的后台任务数量；单任务模式为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `mode`: 本次输出读取模式：tail、range 或 mixed [type: `string`]" expected-block))
    (is (search "  - `status`: 后台任务当前状态；批量模式下若存在多种状态则为 mixed [type: `string`]" expected-block))
    (is (search "  - `running`: 后台任务当前是否仍在运行；批量模式下表示是否仍有任一任务运行 [type: `boolean`]" expected-block))
    (is (search "  - `stopped`: 后台任务是否被显式停止；批量模式下表示是否全部已停止 [type: `boolean`]" expected-block))
    (is (search "  - `outputPath`: 单任务模式下后台任务输出日志路径；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "  - `linesRequested`: 共享请求下的输出窗口行数；按任务定制且不一致时为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `requestedStartLine`: 本次请求的起始行号；tail 模式下为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `requestedEndLine`: 本次请求的结束行号；tail 模式下为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `followSeconds`: 本次请求的 follow 秒数；未指定时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `waitUntilFinished`: 共享请求是否阻塞直到后台任务结束；按任务定制且不一致时为 null [type: `boolean`] [optional] [nullable]" expected-block))
    (is (search "  - `startLine`: 单任务模式下本次返回内容的起始行号；无内容或批量模式时为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `endLine`: 单任务模式下本次返回内容的结束行号；无内容或批量模式时为 null [type: `integer`] [min: `1`] [optional] [nullable]" expected-block))
    (is (search "  - `totalLines`: 单任务模式下当前后台输出日志总行数；批量模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `runningCount`: 批量模式下仍在运行的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `stoppedCount`: 批量模式下已停止的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `completedCount`: 批量模式下已完成的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `failedCount`: 批量模式下已失败的后台任务数量；单任务模式为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `tasks`: 批量模式下的逐任务输出结果数组；单任务模式为 null [type: `array`] [optional] [nullable] [closed]" expected-block))
    (is (search "  - `content`: 单任务模式下按绝对行号编号后的输出内容；批量模式为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "- Error Output Schema: `text`: shell task output failed output; `json`: `error`, `code` [closed]" expected-block))
    (is (search "  - `error`: 后台 shell 任务输出失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `shell`" expected-block))
    (is (equal (%normalize-generated-block-lines generated-block)
               (%normalize-generated-block-lines expected-block)))))
