;;;; tests/contract/cli-help-contract-test.lisp - CLI 帮助契约测试
(in-package :cl-cc/tests)

(def-suite cli-help-contract-test :in cl-cc-suite)

(in-suite cli-help-contract-test)

(defun %extract-generated-readme-section (contents)
  (let* ((start-marker "<!-- BEGIN GENERATED COMMAND REFERENCE -->")
         (end-marker "<!-- END GENERATED COMMAND REFERENCE -->")
         (start (search start-marker contents))
         (end (search end-marker contents)))
    (when (and start end)
      (string-trim '(#\Space #\Tab #\Newline #\Return)
                   (subseq contents
                           (+ start (length start-marker))
                           end)))))

(defun %normalize-line-endings (text)
  (remove #\Return text))

(defun %normalize-generated-block-lines (text)
  (remove-if (lambda (line) (string= line ""))
             (mapcar (lambda (line)
                       (string-right-trim '(#\Space #\Tab)
                                          (substitute #\Space #\Tab line)))
                     (uiop:split-string (%normalize-line-endings text) :separator '(#\Newline)))))

(test cli-help-output-contract
  (let ((help-output (cl-cc:render-help)))
    (is (search "Usage:" help-output))
    (is (search "docs sync-reference [<output-path>] [--check] [--output-format <output-format>]" help-output))
    (is (search "run --fixture <fixture-id>... [--output-format <output-format>]" help-output))
    (is (search "session start [--session-id <session-id>] [--history-index <history-index>] [--output-format <output-format>]" help-output))
    (is (search "session resume <session-id-or-path> [--output-format <output-format>]" help-output))
    (is (search "--check  仅检查命令参考是否需要同步，不写回文件" help-output))
    (is (search "-o, --output-format <output-format>  指定输出格式: text 或 json [default: text]" help-output))
    (is (search "cl-cc --help" help-output))
    (is (search "cl-cc -h" help-output))
    (is (search "cl-cc help" help-output))
    (is (search "-i, --session-id <session-id>  显式指定新会话 ID" help-output))
    (is (search "--history-index <history-index>  设置初始历史索引" help-output))
    (is (search "-o, --output-format <output-format>  指定输出格式: text 或 json [default: text]" help-output))
    (is (search "--pretty  以多行缩进格式输出 JSON [requires: --output-format=json] [conflicts: --compact]" help-output))
    (is (search "--compact  以紧凑单行格式输出 JSON [requires: --output-format=json] [conflicts: --pretty]" help-output))
    (is (search "-t, --tool <tool-id>  覆盖自动工具选择并按给定顺序执行 [repeatable]" help-output))))

(test generated-command-reference-contract
  (let* ((readme (uiop:read-file-string "README.md"))
         (generated-block (%extract-generated-readme-section readme))
         (expected-block (string-trim '(#\Space #\Tab #\Newline #\Return)
                                      (cl-cc:render-command-reference-markdown))))
    (is (not (null generated-block)))
    (is (search "- Output Schema: `text`: result message; `json`: `path`, `status`, `checkOnly`, `updated`, `needsSync`, `durationSeconds`, `exitCode` [closed]" expected-block))
    (is (search "- JSON Fields:" expected-block))
    (is (search "  - `path`: 目标文档路径 [type: `string`]" expected-block))
    (is (search "  - `status`: 同步状态: synced、in-sync 或 drift [type: `string`] [allowed: `synced`, `in-sync`, `drift`]" expected-block))
    (is (search "  - `durationSeconds`: 本次 docs sync 执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "  - `exitCode`: 命令退出码 [type: `integer`] [min: `0`] [max: `255`]" expected-block))
    (is (search "- Output Schema: `text`: fixture execution summary; `json`: `status`, `fixtureCount`, `successfulCount`, `failedCount`, `durationSeconds`, `statusCounts`, `ok`, `exitCode`, `results` [closed]" expected-block))
    (is (search "  - `status`: 聚合结果状态 [type: `string`] [allowed-when-zero: `exitCode` => `success`] [allowed-when-nonzero: `exitCode` => `partial`, `failed`, `denied`, `not-found`] [allowed: `success`, `partial`, `failed`, `denied`, `not-found`]" expected-block))
    (is (search "  - `fixtureCount`: 本次执行的 fixture 数量 [type: `integer`] [min: `0`] [count-of: `results`] [sum-of: `statusCounts.success`, `statusCounts.failed`, `statusCounts.partial`, `statusCounts.denied`, `statusCounts.not-found`, `statusCounts.unknown`]" expected-block))
    (is (search "  - `successfulCount`: 成功 fixture 数量 [type: `integer`] [min: `0`] [matches: `statusCounts.success`]" expected-block))
    (is (search "  - `failedCount`: 失败 fixture 数量 [type: `integer`] [min: `0`] [matches: `statusCounts.failed`]" expected-block))
    (is (search "  - `durationSeconds`: 本次 run 聚合执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "  - `results`: 逐 fixture 的结果记录，包含稳定文本摘要与 toolResults [type: `array`] [min-items: `1`] [closed]" expected-block))
    (is (search "  - `statusCounts`: 各状态计数映射" expected-block))
    (is (search "  - `statusCounts`: 各状态计数映射 [type: `object`] [closed]" expected-block))
    (is (search "  - `ok`: 是否全部成功 [type: `boolean`] [true-when-zero: `exitCode`]" expected-block))
    (is (search "    - `success`: 成功 fixture 数量 [type: `integer`] [min: `0`] [matches-when: `status` = `success` => `fixtureCount`]" expected-block))
    (is (search "    - `failed`: 失败 fixture 数量 [type: `integer`] [min: `0`] [matches-when: `status` = `failed` => `fixtureCount`]" expected-block))
    (is (search "    - `partial`: 混合结果 fixture 数量" expected-block))
    (is (search "    - `denied`: 权限拒绝 fixture 数量 [type: `integer`] [min: `0`] [matches-when: `status` = `denied` => `fixtureCount`]" expected-block))
    (is (search "    - `not-found`: 工具未找到 fixture 数量 [type: `integer`] [min: `0`] [matches-when: `status` = `not-found` => `fixtureCount`]" expected-block))
    (is (search "    - `unknown`: 未归类 fixture 数量" expected-block))
    (is (search "  - `fixtureId`: fixture 标识 [type: `string`]" expected-block))
    (is (search "  - `status`: 该 fixture 的聚合状态" expected-block))
    (is (search "  - `durationSeconds`: 该 fixture 执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "  - `result`: 兼容既有 golden 的稳定文本摘要" expected-block))
    (is (search "  - `toolResults`: 逐工具尝试记录 [type: `array`] [min-items: `1`] [closed]" expected-block))
    (is (search "    - `toolId`: 工具标识" expected-block))
    (is (search "    - `status`: 该次工具尝试状态 [type: `string`] [allowed: `success`, `failed`, `denied`, `not-found`]" expected-block))
    (is (search "    - `durationSeconds`: 该次工具尝试执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "    - `output`: 按工具 output-schema 或 error-output-schema 派生的结构化输出，字段集合由工具定义直接提供 [type: `object`] [optional] [nullable] [closed]" expected-block))
    (is (search "      - `echo-tool.result`: 工具返回的回显结果 [type: `string`]" expected-block))
    (is (search "      - `failing-tool.error`: 失败摘要消息 [type: `string`]" expected-block))
    (is (search "      - `failing-tool.code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "    - `error`: 失败时的人类可读摘要，成功时为 null [type: `string`] [optional] [nullable]" expected-block))
    (is (search "    - `errorCode`: 稳定错误码，成功时为 null [type: `string`] [allowed: `FAIL`, `PERMISSION-DENIED`, `TOOL-NOT-FOUND`] [optional] [nullable]" expected-block))
    (is (search "- Output Schema: `text`: session start message; `json`: `status`, `sessionId`, `historyIndex`, `sessionStatus`, `durationSeconds`, `exitCode` [closed]" expected-block))
    (is (search "  - `sessionId`: 新会话 ID [type: `string`]" expected-block))
    (is (search "  - `status`: 结果状态，当前固定为 success [type: `string`] [allowed: `success`]" expected-block))
    (is (search "  - `historyIndex`: 初始历史索引，未指定时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `sessionStatus`: 会话状态，当前通常为 active [type: `string`] [allowed: `active`] [optional] [nullable]" expected-block))
    (is (search "  - `durationSeconds`: 本次 session start 执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "  - `exitCode`: 命令退出码 [type: `integer`] [min: `0`] [max: `255`]" expected-block))
    (is (search "- Output Schema: `text`: session resume message; `json`: `status`, `sessionId`, `historyIndex`, `sessionStatus`, `durationSeconds`, `exitCode` [closed]" expected-block))
    (is (search "  - `historyIndex`: 恢复快照中的历史索引，缺失时为 null [type: `integer`] [min: `0`] [optional] [nullable]" expected-block))
    (is (search "  - `sessionStatus`: 恢复后的会话状态 [type: `string`] [allowed: `active`] [optional] [nullable]" expected-block))
    (is (search "  - `durationSeconds`: 本次 session resume 执行时长（秒） [type: `number`] [min: `0`]" expected-block))
    (is (search "  - `exitCode`: 命令退出码 [type: `integer`] [min: `0`] [max: `255`]" expected-block))
    (is (search "## 工具参考" expected-block))
    (is (search "### `echo-tool`" expected-block))
    (is (search "- Input Schema: `text`: input string; `json`: `input` [closed]" expected-block))
    (is (search "- Input JSON Fields:" expected-block))
    (is (search "  - `input`: 待回显的输入字符串 [type: `string`]" expected-block))
    (is (search "- Output Schema: `text`: echoed string; `json`: `result` [closed]" expected-block))
    (is (search "- Output JSON Fields:" expected-block))
    (is (search "  - `result`: 工具返回的回显结果 [type: `string`]" expected-block))
    (is (search "- Permission Profile: `default`" expected-block))
    (is (search "### `failing-tool`" expected-block))
    (is (search "- Input Schema: `text`: input string; `json`: `input` [closed]" expected-block))
    (is (search "  - `input`: 触发失败路径的输入字符串 [type: `string`]" expected-block))
    (is (search "- Output Schema: `text`: no successful output" expected-block))
    (is (search "- Error Output Schema: `text`: failed output; `json`: `error`, `code` [closed]" expected-block))
    (is (search "- Error JSON Fields:" expected-block))
    (is (search "  - `error`: 失败摘要消息 [type: `string`]" expected-block))
    (is (search "  - `code`: 稳定错误码 [type: `string`]" expected-block))
    (is (search "- Failure Modes: `failed`" expected-block))
    (is (equal (%normalize-generated-block-lines generated-block)
               (%normalize-generated-block-lines expected-block)))))
