;;;; src/models/command-definition.lisp
(in-package :cl-cc.models)

(defclass command-definition ()
  ((name :initarg :name :accessor command-name :documentation "命令名称")
   (aliases :initarg :aliases :accessor command-aliases :documentation "别名列表")
   (arguments-schema :initarg :arguments-schema :accessor command-arguments-schema :documentation "参数模式")
   (output-schema :initarg :output-schema :accessor command-output-schema :documentation "输出模式")
   (summary :initarg :summary :accessor command-summary :documentation "帮助摘要")
   (handler-symbol :initarg :handler-symbol :accessor command-handler-symbol :documentation "处理函数符号")
   (permission-profile :initarg :permission-profile :accessor command-permission-profile :documentation "权限类别")
   (group :initarg :group :initform nil :accessor command-group :documentation "命令分组")
   (source :initarg :source :initform nil :accessor command-source :documentation "命令来源")
   (hidden-p :initarg :hidden-p :initform nil :accessor command-hidden-p :documentation "是否在帮助/参考中隐藏")
   (beta-p :initarg :beta-p :initform nil :accessor command-beta-p :documentation "是否为 beta 命令")
   (requires-auth-p :initarg :requires-auth-p :initform nil :accessor command-requires-auth-p :documentation "是否要求认证")))
