;;;; tests/unit/command-dispatch-test.lisp - 命令注册与分发单元测试
(in-package :cl-cc/tests)

(def-suite command-dispatch-test :in cl-cc-suite)

(in-suite command-dispatch-test)

(test command-key-resolution
  (is (string= (cl-cc.core:command-key-from-argv '("--help")) "help"))
  (is (string= (cl-cc.core:command-key-from-argv '("docs" "sync")) "docs sync-reference"))
  (is (string= (cl-cc.core:command-key-from-argv '("run" "--help")) "help"))
  (is (string= (cl-cc.core:command-key-from-argv '("-h")) "help"))
  (is (string= (cl-cc.core:command-key-from-argv '("session" "start")) "session start"))
  (is (string= (cl-cc.core:command-key-from-argv '("s" "start")) "session start"))
  (is (string= (cl-cc.core:command-key-from-argv '("session" "resume" "abc")) "session resume"))
  (is (string= (cl-cc.core:command-key-from-argv '("s" "resume" "abc")) "session resume"))
  (is (string= (cl-cc.core:command-key-from-argv '("run" "--fixture" "test")) "run --fixture"))
  (is (string= (cl-cc.core:command-key-from-argv '("r" "--fixture" "test")) "run --fixture")))

(test help-through-registry
  (cl-cc.core:ensure-default-commands)
  (let ((definition (cl-cc.core:find-command "help")))
    (is (typep definition 'cl-cc.models:command-definition))
    (is (string= (cl-cc.models:command-summary definition) "显示 CLI 帮助")))
  (let ((output (capture-output (lambda () (cl-cc:main "--help")))))
    (is (search "Usage:" output))
    (is (search "docs sync-reference [<output-path>] [--check] [--output-format <output-format>]" output))
    (is (search "run --fixture <fixture-id>... [--output-format <output-format>]" output))
    (is (search "session start [--session-id <session-id>] [--history-index <history-index>]" output))
    (is (search "[default: text]" output))
    (is (search "[requires: --output-format=json]" output))))

(test docs-sync-reference-through-registry
  (let ((path (uiop:native-namestring
               (uiop:merge-pathnames* "generated-reference-test.md"
                                      (uiop:temporary-directory)))))
    (unwind-protect
         (progn
           (with-open-file (stream path :direction :output :if-exists :supersede :if-does-not-exist :create)
             (write-string (format nil "before~%<!-- BEGIN GENERATED COMMAND REFERENCE -->~%old~%<!-- END GENERATED COMMAND REFERENCE -->~%after~%")
                           stream))
           (let ((output (capture-output (lambda () (cl-cc:main "docs" "sync" path)))))
             (is (search "命令参考已同步" output)))
           (let ((contents (uiop:read-file-string path)))
             (is (search "### `docs sync-reference`" contents))
             (is (search "### `run --fixture`" contents))
             (is (search "before" contents))
             (is (search "after" contents))))
      (when (probe-file path)
        (delete-file path)))))

(test docs-sync-reference-check-mode
  (let ((path (uiop:native-namestring
               (uiop:merge-pathnames* "generated-reference-check-test.md"
                                      (uiop:temporary-directory)))))
    (unwind-protect
         (progn
           (with-open-file (stream path :direction :output :if-exists :supersede :if-does-not-exist :create)
             (write-string (format nil "before~%<!-- BEGIN GENERATED COMMAND REFERENCE -->~%old~%<!-- END GENERATED COMMAND REFERENCE -->~%after~%")
                           stream))
           (let ((before-check (uiop:read-file-string path)))
             (is (= (cl-cc:main "docs" "sync" path "--check") 1))
             (is (string= before-check (uiop:read-file-string path))))
           (let ((json-output (capture-output (lambda () (cl-cc:main "docs" "sync" path "--check" "--output-format" "json")))))
             (is (search "\"status\":\"drift\"" json-output))
             (is (search "\"checkOnly\":true" json-output))
             (is (search "\"updated\":false" json-output))
             (is (search "\"needsSync\":true" json-output))
             (is (search "\"durationSeconds\":" json-output))
             (is (search "\"exitCode\":1" json-output)))
           (is (= (cl-cc:main "docs" "sync" path) 0))
           (let ((output (capture-output (lambda () (cl-cc:main "docs" "sync" path "--check")))))
             (is (search "命令参考已是最新" output))
             (is (not (search "需要同步" output))))
           (let ((json-output (capture-output (lambda () (cl-cc:main "docs" "sync" path "--check" "-o" "json")))))
             (is (search "\"status\":\"in-sync\"" json-output))
             (is (search "\"checkOnly\":true" json-output))
             (is (search "\"updated\":false" json-output))
             (is (search "\"needsSync\":false" json-output))
             (is (search "\"durationSeconds\":" json-output))
             (is (search "\"exitCode\":0" json-output))))
      (when (probe-file path)
        (delete-file path)))))

(test docs-sync-reference-json-output
  (let ((path (uiop:native-namestring
               (uiop:merge-pathnames* "generated-reference-json-test.md"
                                      (uiop:temporary-directory)))))
    (unwind-protect
         (progn
           (with-open-file (stream path :direction :output :if-exists :supersede :if-does-not-exist :create)
             (write-string (format nil "before~%<!-- BEGIN GENERATED COMMAND REFERENCE -->~%old~%<!-- END GENERATED COMMAND REFERENCE -->~%after~%")
                           stream))
           (let ((output (capture-output (lambda () (cl-cc:main "docs" "sync" path "--output-format" "json")))))
             (is (search "\"status\":\"synced\"" output))
             (is (search "\"checkOnly\":false" output))
             (is (search "\"updated\":true" output))
             (is (search "\"needsSync\":false" output))
             (is (search "\"durationSeconds\":" output))
             (is (search "\"exitCode\":0" output))
             (is (search "\"path\":" output)))
           (let ((output (capture-output (lambda () (cl-cc:main "docs" "sync" path "--output-format" "json")))))
             (is (search "\"status\":\"in-sync\"" output))
             (is (search "\"checkOnly\":false" output))
             (is (search "\"updated\":false" output))
             (is (search "\"needsSync\":false" output))
             (is (search "\"durationSeconds\":" output))
             (is (search "\"exitCode\":0" output)))
           (is (= (cl-cc:main "docs" "sync" path "--output-format" "xml") 1)))
      (when (probe-file path)
        (delete-file path)))))

(test dispatch-through-registry
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "test")))))
    (is (search "夹具执行结果" output))
    (is (search "[SUCCESS]" output)))
  (let ((output (capture-output (lambda () (cl-cc:main "r" "--fixture" "test")))))
    (is (search "夹具执行结果" output))
    (is (search "[SUCCESS]" output)))
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "test" "--output-format=json")))))
    (is (not (search "[DEBUG]" output)))
    (is (search "\"status\":\"success\"" output))
    (is (search "\"fixtureCount\":1" output))
    (is (search "\"successfulCount\":1" output))
    (is (search "\"failedCount\":0" output))
    (is (search "\"durationSeconds\":" output))
    (is (search "\"statusCounts\":{" output))
    (is (search "\"success\":1" output))
    (is (search "\"failed\":0" output))
    (is (search "\"ok\":true" output))
    (is (search "\"exitCode\":0" output))
    (is (search "\"results\":[{\"fixtureId\":\"test\"" output))
    (is (search "\"toolResults\":[{\"toolId\":\"echo-tool\"" output))
    (is (search "\"durationSeconds\":" output))
    (is (search "\"output\":{\"result\":\"fixture-input-test\"}" output)))
  (is (= (cl-cc:main "run" "--fixture" "test" "--output-format=json") 0))
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "test" "--output-format" "json" "--pretty")))))
    (is (search "  \"status\": \"success\"" output))
    (is (search "  \"fixtureCount\": 1" output))
    (is (search "  \"successfulCount\": 1" output))
    (is (search "  \"failedCount\": 0" output))
    (is (search "  \"durationSeconds\": " output))
    (is (search "  \"statusCounts\": {" output))
    (is (search "    \"success\": 1" output))
    (is (search "    \"failed\": 0" output))
    (is (search "  \"ok\": true" output))
    (is (search "    \"fixtureId\": \"test\"" output))
    (is (search "    \"durationSeconds\": " output))
    (is (search "      \"toolId\": \"echo-tool\"" output))
    (is (search "      \"durationSeconds\": " output))
    (is (search "      \"output\": {\"result\":\"fixture-input-test\"}" output)))
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "test" "--pretty")))))
    (is (search "  \"status\": \"success\"" output))
    (is (search "  \"fixtureCount\": 1" output))
    (is (search "  \"successfulCount\": 1" output))
    (is (search "  \"durationSeconds\": " output))
    (is (search "    \"fixtureId\": \"test\"" output))
    (is (search "    \"durationSeconds\": " output))
    (is (search "      \"toolId\": \"echo-tool\"" output)))
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "test" "--compact")))))
    (is (search "\"status\":\"success\"" output))
    (is (search "\"fixtureCount\":1" output))
    (is (search "\"successfulCount\":1" output))
    (is (search "\"failedCount\":0" output))
    (is (search "\"durationSeconds\":" output))
    (is (search "\"statusCounts\":{" output))
    (is (search "\"results\":[{\"fixtureId\":\"test\"" output))
    (is (search "\"toolResults\":[{\"toolId\":\"echo-tool\"" output)))
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "test" "-o" "json" "-t" "failing-tool")))))
    (is (not (search "[DEBUG]" output)))
    (is (search "\"status\":\"failed\"" output))
    (is (search "\"successfulCount\":0" output))
    (is (search "\"failedCount\":1" output))
    (is (search "\"durationSeconds\":" output))
    (is (search "\"statusCounts\":{" output))
    (is (search "\"success\":0" output))
    (is (search "\"failed\":1" output))
    (is (search "\"exitCode\":1" output))
    (is (search "\"ok\":false" output))
    (is (search "\"error\":\"工具执行失败\"" output))
    (is (search "\"errorCode\":\"FAIL\"" output)))
  (is (= (cl-cc:main "run" "--fixture" "test" "-o" "json" "-t" "failing-tool") 1))
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "restricted" "-o" "json" "-t" "echo-tool")))))
    (is (search "\"status\":\"denied\"" output))
    (is (search "\"denied\":1" output))
    (is (search "\"exitCode\":1" output))
    (is (search "\"ok\":false" output))
    (is (search "\"errorCode\":\"PERMISSION-DENIED\"" output)))
  (is (= (cl-cc:main "run" "--fixture" "restricted" "-o" "json" "-t" "echo-tool") 1))
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "test" "restricted" "-o" "json" "-t" "echo-tool")))))
    (is (search "\"status\":\"partial\"" output))
    (is (search "\"successfulCount\":1" output))
    (is (search "\"denied\":1" output))
    (is (search "\"ok\":false" output))
    (is (search "\"exitCode\":1" output)))
  (is (= (cl-cc:main "run" "--fixture" "test" "restricted" "-o" "json" "-t" "echo-tool") 1))
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "test" "-o" "json" "-t" "missing-tool")))))
    (is (search "\"status\":\"not-found\"" output))
    (is (search "\"not-found\":1" output))
    (is (search "\"exitCode\":1" output))
    (is (search "\"ok\":false" output))
    (is (search "\"errorCode\":\"TOOL-NOT-FOUND\"" output)))
  (is (= (cl-cc:main "run" "--fixture" "test" "-o" "json" "-t" "missing-tool") 1))
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "test" "-t" "echo-tool")))))
    (is (search "夹具执行结果: [SUCCESS] tool:echo-tool" output)))
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "fail" "-t" "failing-tool" "-t" "echo-tool")))))
    (is (search "夹具执行结果: [SUCCESS] tool:echo-tool" output)))
  (let ((output (capture-output (lambda () (cl-cc:main "run" "--fixture" "test" "fail")))) )
    (is (search "test: [SUCCESS] tool:echo-tool" output))
    (is (search "fail: [SUCCESS] tool:echo-tool" output))))

(test invalid-arguments-through-registry
  (is (= (cl-cc:main "run" "--fixture") 1))
  (is (= (cl-cc:main "s" "resume") 1))
  (is (= (cl-cc:main "session" "start" "--unknown") 1))
  (is (= (cl-cc:main "session" "start" "--output-format" "xml") 1))
  (is (= (cl-cc:main "session" "resume" "resume-user" "--output-format" "xml") 1))
  (is (= (cl-cc:main "run" "--fixture" "test" "--output-format=xml") 1))
  (is (= (cl-cc:main "run" "--fixture" "test" "-t") 1))
  (is (= (cl-cc:main "run" "--fixture" "test" "--output-format" "text" "--pretty") 1))
  (is (= (cl-cc:main "run" "--fixture" "test" "--output-format" "json" "--pretty" "--compact") 1)))

(test named-option-through-registry
  (let ((output (capture-output (lambda () (cl-cc:main "session" "start" "--session-id" "named-session")))))
    (is (search "新会话已创建: named-session" output)))
  (let ((output (capture-output (lambda () (cl-cc:main "session" "start" "-i" "short-session" "--history-index" "3")))))
    (is (search "新会话已创建: short-session" output))
    (is (search "历史索引: 3" output)))
  (let ((output (capture-output (lambda () (cl-cc:main "session" "start" "-i" "json-session" "--history-index" "3" "--output-format" "json")))))
    (is (search "\"status\":\"success\"" output))
    (is (search "\"sessionId\":\"json-session\"" output))
    (is (search "\"historyIndex\":3" output))
    (is (search "\"sessionStatus\":\"active\"" output))
    (is (search "\"durationSeconds\":" output))
    (is (search "\"exitCode\":0" output)))
  (let ((output (capture-output (lambda () (cl-cc:main "session" "resume" "resume-user")))))
    (is (search "会话已恢复: resume-user" output)))
  (let ((output (capture-output (lambda () (cl-cc:main "session" "resume" "resume-user" "--output-format" "json")))))
    (is (search "\"status\":\"success\"" output))
    (is (search "\"sessionId\":\"resume-user\"" output))
    (is (search "\"historyIndex\":null" output))
    (is (search "\"sessionStatus\":\"active\"" output))
    (is (search "\"durationSeconds\":" output))
    (is (search "\"exitCode\":0" output))))

(test typed-option-validation-through-registry
  (is (= (cl-cc:main "session" "start" "--history-index" "abc") 1)))

(test session-loop-summary
  (let* ((session (cl-cc.services:start-session "loop-user"))
      (summary-1 (cl-cc.core:session-loop session))
      (summary-2 (cl-cc.core:session-loop session)))
    (is (equal (getf summary-1 :session-id) "loop-user"))
    (is (eq (getf summary-1 :status) :completed))
    (is (= (getf summary-1 :history-index) 1))
    (is (string= (getf summary-1 :execution-command) "session-loop"))
    (is (= (length (getf summary-1 :history-trail)) 2))
    (is (= (cl-cc.models:session-history-index session) 2))
    (is (eq (getf summary-2 :status) :completed))
    (is (= (getf summary-2 :history-index) 2))
    (is (= (length (getf summary-2 :history-trail)) 3))
    (is (equal (cl-cc.models:session-context-summary session) summary-2))))