;;;; tests/unit/command-registry-metadata-test.lisp
(in-package :cl-cc/tests)

(def-suite command-registry-metadata-test :in cl-cc-suite)
(in-suite command-registry-metadata-test)

(defun %default-command-definition (name)
  (cl-cc.core:find-command name))

(defun %command-json-field-names (definition)
  (mapcar (lambda (field) (getf field :name))
          (getf (cl-cc.models:command-output-schema definition) :json)))

(defun %command-option-keys (definition)
  (mapcar (lambda (option) (getf option :key))
          (getf (cl-cc.models:command-arguments-schema definition) :options)))

(defun %command-positionals (definition)
  (getf (cl-cc.models:command-arguments-schema definition) :positionals))

(defun %first-command-positional (definition)
  (first (%command-positionals definition)))

(defun %command-names ()
  (mapcar #'cl-cc.models:command-name
          (cl-cc.core:list-command-definitions)))

(test default-command-metadata-core-shape
  (cl-cc.core:ensure-default-commands)
  (let ((help (%default-command-definition "help"))
        (docs-sync (%default-command-definition "docs sync-reference"))
    (chat (%default-command-definition "chat"))
        (session-start (%default-command-definition "session start"))
        (session-resume (%default-command-definition "session resume"))
  (session-run (%default-command-definition "session run"))
        (run-fixture (%default-command-definition "run --fixture")))
    (is (typep help 'cl-cc.models:command-definition))
    (is (typep docs-sync 'cl-cc.models:command-definition))
  (is (typep chat 'cl-cc.models:command-definition))
    (is (typep session-start 'cl-cc.models:command-definition))
    (is (typep session-resume 'cl-cc.models:command-definition))
    (is (typep session-run 'cl-cc.models:command-definition))
    (is (typep run-fixture 'cl-cc.models:command-definition))
    (is (string= (cl-cc.models:command-summary help) "显示 CLI 帮助"))
    (is (equal (cl-cc.models:command-aliases docs-sync) '(("docs" "sync"))))
    (is (equal (cl-cc.models:command-aliases chat) '(("c"))))
    (is (equal (cl-cc.models:command-aliases session-start) '(("s" "start"))))
    (is (equal (cl-cc.models:command-aliases session-resume) '(("s" "resume"))))
    (is (equal (cl-cc.models:command-aliases session-run) '(("s" "run"))))
    (is (equal (cl-cc.models:command-aliases run-fixture) '(("r" "--fixture"))))
    (is (eq (cl-cc.models:command-permission-profile run-fixture) :default))))

(test default-command-registration-set
  (cl-cc.core:reset-command-registry)
  (is (= 0 (hash-table-count cl-cc.core:*command-registry*)))
  (cl-cc.core:ensure-default-commands)
  (is (= 7 (hash-table-count cl-cc.core:*command-registry*)))
  (is (equal (%command-names)
       '("chat"
         "docs sync-reference"
         "help"
         "run --fixture"
         "session resume"
         "session run"
         "session start"))))

(test default-command-handler-bindings
      (cl-cc.core:reset-command-registry)
      (cl-cc.core:ensure-default-commands)
  (let ((help (%default-command-definition "help"))
    (chat (%default-command-definition "chat"))
    (docs-sync (%default-command-definition "docs sync-reference"))
    (session-start (%default-command-definition "session start"))
    (session-resume (%default-command-definition "session resume"))
    (session-run (%default-command-definition "session run"))
    (run-fixture (%default-command-definition "run --fixture")))
  (is (eq (cl-cc.models:command-handler-symbol help)
            'cl-cc::handle-help-command))
  (is (eq (cl-cc.models:command-handler-symbol chat)
            'cl-cc::handle-chat-command))
  (is (eq (cl-cc.models:command-handler-symbol docs-sync)
            'cl-cc::handle-docs-sync-reference-command))
  (is (eq (cl-cc.models:command-handler-symbol session-start)
            'cl-cc::handle-session-start-command))
  (is (eq (cl-cc.models:command-handler-symbol session-resume)
            'cl-cc::handle-session-resume-command))
  (is (eq (cl-cc.models:command-handler-symbol session-run)
            'cl-cc::handle-session-run-command))
  (is (eq (cl-cc.models:command-handler-symbol run-fixture)
            'cl-cc::handle-run-fixture-command))
  (is (eq (cl-cc.core:find-command-handler "help")
            (symbol-function 'cl-cc::handle-help-command)))
  (is (eq (cl-cc.core:find-command-handler "chat")
            (symbol-function 'cl-cc::handle-chat-command)))
  (is (eq (cl-cc.core:find-command-handler "docs sync-reference")
            (symbol-function 'cl-cc::handle-docs-sync-reference-command)))
  (is (eq (cl-cc.core:find-command-handler "session start")
            (symbol-function 'cl-cc::handle-session-start-command)))
  (is (eq (cl-cc.core:find-command-handler "session resume")
            (symbol-function 'cl-cc::handle-session-resume-command)))
  (is (eq (cl-cc.core:find-command-handler "session run")
            (symbol-function 'cl-cc::handle-session-run-command)))
  (is (eq (cl-cc.core:find-command-handler "run --fixture")
      (symbol-function 'cl-cc::handle-run-fixture-command)))))

(test default-command-registration-is-idempotent
      (cl-cc.core:reset-command-registry)
      (cl-cc.core:ensure-default-commands)
      (let ((first-count (hash-table-count cl-cc.core:*command-registry*))
            (first-names (%command-names))
            (first-help (%default-command-definition "help")))
        (cl-cc.core:ensure-default-commands)
        (is (= first-count (hash-table-count cl-cc.core:*command-registry*)))
        (is (equal first-names (%command-names)))
        (is (typep first-help 'cl-cc.models:command-definition))
  (is (typep (%default-command-definition "help") 'cl-cc.models:command-definition))))

(test help-command-aliases-remain-stable
      (cl-cc.core:ensure-default-commands)
  (let ((help (%default-command-definition "help")))
  (is (equal (cl-cc.models:command-aliases help)
               '(("--help") ("-h") ("help"))))))

(test default-command-arguments-metadata
  (cl-cc.core:ensure-default-commands)
  (let ((docs-sync (%default-command-definition "docs sync-reference"))
    (chat (%default-command-definition "chat"))
    (session-start (%default-command-definition "session start"))
    (session-resume (%default-command-definition "session resume"))
    (session-run (%default-command-definition "session run"))
    (run-fixture (%default-command-definition "run --fixture")))
    (is (equal (%command-option-keys chat)
               '(:session-path :session-id :tool-ids)))
    (is (equal (%command-option-keys docs-sync)
               '(:check-only :output-format)))
    (is (equal (%command-option-keys session-start)
               '(:session-id :session-path :history-index :output-format)))
    (is (equal (%command-option-keys session-resume)
               '(:output-format)))
    (is (equal (%command-option-keys session-run)
          '(:session-path :tool-ids :output-format)))
    (is (equal (%command-option-keys run-fixture)
               '(:output-format :pretty-json :compact-json :tool-ids)))
     (is (equal (getf (%first-command-positional session-resume) :name)
               "<session-id-or-path>"))
     (is (getf (%first-command-positional session-resume) :required))
     (is (equal (getf (%first-command-positional session-run) :name)
           "<session-id-or-path>"))
     (is (getf (%first-command-positional session-run) :required))
         (is (equal (getf (%first-command-positional chat) :name)
            "<session-id-or-path>"))
         (is (not (getf (%first-command-positional chat) :required)))
         (is (equal (getf (second (%command-positionals session-run)) :name)
            "<user-input>"))
         (is (not (getf (second (%command-positionals session-run)) :required)))
    (is (equal (mapcar (lambda (spec) (getf spec :name))
                  (%command-positionals run-fixture))
               '("<fixture-id>")))
     (is (getf (%first-command-positional run-fixture) :required))
     (is (getf (%first-command-positional run-fixture) :repeatable))))

(test default-command-output-schema-metadata
  (cl-cc.core:ensure-default-commands)
    (let ((chat (%default-command-definition "chat"))
        (docs-sync (%default-command-definition "docs sync-reference"))
        (session-start (%default-command-definition "session start"))
        (session-resume (%default-command-definition "session resume"))
      (session-run (%default-command-definition "session run"))
        (run-fixture (%default-command-definition "run --fixture")))
    (is (equal (getf (cl-cc.models:command-output-schema chat) :text)
               "interactive chat transcript"))
    (is (getf (cl-cc.models:command-output-schema docs-sync) :closed))
    (is (equal (%command-json-field-names docs-sync)
               '("path" "status" "checkOnly" "updated" "needsSync" "durationSeconds" "exitCode")))
    (is (equal (%command-json-field-names session-start)
               '("status" "sessionId" "historyIndex" "sessionStatus" "sessionPath" "saved" "durationSeconds" "exitCode")))
    (is (equal (%command-json-field-names session-resume)
               '("status" "sessionId" "historyIndex" "sessionStatus" "durationSeconds" "exitCode")))
    (is (equal (%command-json-field-names session-run)
          '("status" "sessionId" "historyIndex" "sessionStatus" "input" "executionStatus" "selectedTools" "executionPlan" "result" "toolResults" "sessionPath" "saved" "durationSeconds" "exitCode")))
    (is (equal (%command-json-field-names run-fixture)
               '("status" "fixtureCount" "successfulCount" "failedCount" "durationSeconds" "statusCounts" "ok" "exitCode" "results")))))