;;;; tests/unit/shell-task-list-tool-test.lisp - shell-task-list-tool 单元测试
(in-package :cl-cc/tests)

(def-suite shell-task-list-tool-test :in cl-cc-suite)

(in-suite shell-task-list-tool-test)

(test normalized-shell-task-list-input-parses-natural-language-and-structured-input
  (is (equal (cl-cc.tools::%normalized-shell-task-list-input "shell task list")
             '(:status :all :task-id-prefix nil :directory-contains nil :termination-reason nil)))
  (is (equal (cl-cc.tools::%normalized-shell-task-list-input "列出后台任务")
             '(:status :all :task-id-prefix nil :directory-contains nil :termination-reason nil)))
  (is (equal (cl-cc.tools::%normalized-shell-task-list-input "shell task list :: running")
             '(:status :running :task-id-prefix nil :directory-contains nil :termination-reason nil)))
  (is (equal (cl-cc.tools::%normalized-shell-task-list-input "列出运行中的后台任务")
             '(:status :running :task-id-prefix nil :directory-contains nil :termination-reason nil)))
  (is (equal (cl-cc.tools::%normalized-shell-task-list-input "shell task list :: status=failed :: task=shell-task-12 :: dir=temp")
             '(:status :failed :task-id-prefix "shell-task-12" :directory-contains "temp" :termination-reason nil)))
  (is (equal (cl-cc.tools::%normalized-shell-task-list-input "shell task list :: termination=interrupt")
             '(:status :all :task-id-prefix nil :directory-contains nil :termination-reason "interrupt")))
  (is (equal (cl-cc.tools::%normalized-shell-task-list-input '(:all t))
             '(:status :all :task-id-prefix nil :directory-contains nil :termination-reason nil)))
  (is (equal (cl-cc.tools::%normalized-shell-task-list-input '(:status "failed"))
             '(:status :failed :task-id-prefix nil :directory-contains nil :termination-reason nil)))
  (is (equal (cl-cc.tools::%normalized-shell-task-list-input '(:status "failed" :taskIdPrefix "shell-task-12" :directoryContains "temp"))
             '(:status :failed :task-id-prefix "shell-task-12" :directory-contains "temp" :termination-reason nil)))
  (is (equal (cl-cc.tools::%normalized-shell-task-list-input '(:terminationReason "stop"))
             '(:status :all :task-id-prefix nil :directory-contains nil :termination-reason "stop")))
  (is (equal (cl-cc.tools::%normalized-shell-task-list-input nil)
             '(:status :all :task-id-prefix nil :directory-contains nil :termination-reason nil))))

(test shell-task-list-tool-lists-current-background-tasks
  (let* ((directory-root (uiop:temporary-directory))
         (directory-a-path (uiop:merge-pathnames* "shell-task-list-a/" directory-root))
         (directory-b-path (uiop:merge-pathnames* "shell-task-list-b/" directory-root))
         (directory-a (uiop:native-namestring (uiop:ensure-directory-pathname directory-a-path)))
         (directory-b (uiop:native-namestring (uiop:ensure-directory-pathname directory-b-path)))
         (directory-setup-a (ensure-directories-exist (uiop:merge-pathnames* "touch.txt" directory-a-path)))
         (directory-setup-b (ensure-directories-exist (uiop:merge-pathnames* "touch.txt" directory-b-path)))
         (running-result (cl-cc.tools:shell-tool (list :command "Start-Sleep -Seconds 5; [Console]::Out.Write('shell-task-list-running')"
                                                       :directory directory-a
                                                       :background t)))
         (completed-result (cl-cc.tools:shell-tool (list :command "[Console]::Out.Write('shell-task-list-completed')"
                                                         :directory directory-b
                                                         :background t)))
         (stopped-result (cl-cc.tools:shell-tool (list :command "Start-Sleep -Seconds 5; [Console]::Out.Write('shell-task-list-stopped')"
                                                       :directory directory-a
                                                       :background t)))
         (interrupted-result (cl-cc.tools:shell-tool (list :command "Start-Sleep -Seconds 5; [Console]::Out.Write('shell-task-list-interrupt')"
                                                           :directory directory-b
                                                           :background t)))
         (running-task-id (getf running-result :background-task-id))
         (completed-task-id (getf completed-result :background-task-id))
         (stopped-task-id (getf stopped-result :background-task-id))
         (interrupted-task-id (getf interrupted-result :background-task-id))
         (running-output-path (getf running-result :output-path))
         (completed-output-path (getf completed-result :output-path))
         (stopped-output-path (getf stopped-result :output-path))
         (interrupted-output-path (getf interrupted-result :output-path)))
          (declare (ignore directory-setup-a directory-setup-b))
    (unwind-protect
         (progn
           (sleep 0.4)
           (cl-cc.tools:shell-task-tool (list :task-id stopped-task-id :action :stop))
           (cl-cc.tools:shell-task-tool (list :task-id interrupted-task-id :action :interrupt))
           (let* ((result (cl-cc.tools:shell-task-list-tool nil))
                  (tasks (getf result :tasks))
                  (running-task (find running-task-id tasks :key (lambda (task)
                                                                   (getf task :task-id))
                                      :test #'string=))
                  (completed-task (find completed-task-id tasks :key (lambda (task)
                                                                       (getf task :task-id))
                                        :test #'string=))
                  (stopped-task (find stopped-task-id tasks :key (lambda (task)
                                                                   (getf task :task-id))
                                      :test #'string=))
                  (interrupted-task (find interrupted-task-id tasks :key (lambda (task)
                                                                          (getf task :task-id))
                                         :test #'string=)))
             (is (>= (getf result :total-count) 4))
             (is (string= (getf result :status-filter) "all"))
             (is (null (getf result :task-id-prefix-filter)))
             (is (null (getf result :directory-contains-filter)))
             (is (null (getf result :termination-reason-filter)))
             (is (>= (getf result :running-count) 1))
             (is (>= (getf result :completed-count) 1))
             (is (not (null running-task)))
             (is (not (null completed-task)))
             (is (not (null stopped-task)))
             (is (not (null interrupted-task)))
             (is (string= (getf running-task :status) "running"))
             (is (getf running-task :running))
             (is (not (getf running-task :stall-detected)))
             (is (null (getf running-task :stall-detected-at)))
             (is (null (getf running-task :stall-prompt-line)))
             (is (null (getf running-task :termination-reason)))
             (is (null (getf running-task :ended-at)))
             (is (string= (getf completed-task :status) "completed"))
             (is (not (getf completed-task :stall-detected)))
             (is (string= (getf completed-task :termination-reason) "exit"))
             (is (stringp (getf completed-task :ended-at)))
             (is (string= (getf stopped-task :status) "stopped"))
             (is (not (getf stopped-task :stall-detected)))
             (is (string= (getf stopped-task :termination-reason) "stop"))
             (is (stringp (getf stopped-task :ended-at)))
             (is (string= (getf interrupted-task :status) "stopped"))
             (is (not (getf interrupted-task :stall-detected)))
             (is (string= (getf interrupted-task :termination-reason) "interrupt"))
             (is (stringp (getf interrupted-task :ended-at)))
             (is (not (getf completed-task :running)))
             (let* ((running-only (cl-cc.tools:shell-task-list-tool '(:status :running)))
                    (running-only-tasks (getf running-only :tasks)))
               (is (string= (getf running-only :status-filter) "running"))
               (is (= (getf running-only :total-count) (getf running-only :running-count)))
               (is (every (lambda (task)
                            (string= (getf task :status) "running"))
                          running-only-tasks)))
             (let* ((task-filtered (cl-cc.tools:shell-task-list-tool (list :task-id-prefix running-task-id)))
                    (task-filtered-tasks (getf task-filtered :tasks)))
               (is (string= (getf task-filtered :task-id-prefix-filter) running-task-id))
               (is (= (getf task-filtered :total-count) 1))
               (is (string= (getf (first task-filtered-tasks) :task-id) running-task-id)))
             (let* ((directory-filtered (cl-cc.tools:shell-task-list-tool (list :directory-contains "shell-task-list-b")))
                    (directory-filtered-tasks (getf directory-filtered :tasks)))
               (is (string= (getf directory-filtered :directory-contains-filter) "shell-task-list-b"))
               (is (= (getf directory-filtered :total-count) 2))
               (is (= (length directory-filtered-tasks) 2)))
             (let* ((termination-filtered (cl-cc.tools:shell-task-list-tool '(:termination-reason "interrupt")))
                    (termination-filtered-tasks (getf termination-filtered :tasks)))
               (is (string= (getf termination-filtered :termination-reason-filter) "interrupt"))
               (is (= (getf termination-filtered :total-count) 1))
               (is (= (length termination-filtered-tasks) 1))
               (is (string= (getf (first termination-filtered-tasks) :task-id) interrupted-task-id)))))
      (when running-task-id
        (remhash running-task-id cl-cc.tools::*shell-background-task-registry*))
      (when completed-task-id
        (remhash completed-task-id cl-cc.tools::*shell-background-task-registry*))
      (when stopped-task-id
        (remhash stopped-task-id cl-cc.tools::*shell-background-task-registry*))
      (when interrupted-task-id
        (remhash interrupted-task-id cl-cc.tools::*shell-background-task-registry*))
      (sleep 0.2)
      (when (and running-output-path (probe-file running-output-path))
        (ignore-errors (delete-file running-output-path)))
      (when (and completed-output-path (probe-file completed-output-path))
        (ignore-errors (delete-file completed-output-path)))
      (when (and stopped-output-path (probe-file stopped-output-path))
        (ignore-errors (delete-file stopped-output-path)))
      (when (and interrupted-output-path (probe-file interrupted-output-path))
        (ignore-errors (delete-file interrupted-output-path))))))